### ISSUE TITLE
Ontology for Innovation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#1]
http://www.lexicater.co.uk/vocabularies/innovation/ns.html

I wonder about your view on this ontology

![inno](http://www.lexicater.co.uk/vocabularies/innovation/innovation.jpg)

I like that it tries to express concepts like **Need, Problem, Symptom,  Benefit, DevelopmentStage, Disruption, Improvement, Usage** etc.

**Comment by bhaugen** [comment]
I like Need, Problem, Symptom, DevelopmentStage and Usage.

Am suspicious of Innovator and Innovation and Disruption, as being buzzwords of the VC startup class. See also [where do good ideas come from](http://www.goodreads.com/work/quotes/12645873-where-good-ideas-come-from-the-natural-history-of-innovation).

I also don't think the model is very good ontologically.  I think  things are a lot more deeply interconnected than that. But early-stage R&D is an arena that we are thinking a lot about these days, so I appreciate the link and will study this model more as we get our own model changes together a bit more and maybe be able to make some contrasts.

To explain more about "not very good ontologically": I see a bunch of models these days that connect some of their concepts to "Thing" and think that makes them into an ontology. Usually many layers of upper ontology would appear between Thing and whatever they called Thing if their model was really ontological. And then of course the several upper ontologies disagree with each other about those layers, but that's another issue...

**Comment by elf-pavlik** [comment]
@bhaugen did you get chance to read http://workingontologist.org ? if not yet i strongly recommend giving it high priority!

Just to check that we interpret this 'connecting to Thing' the same way. If you look at [rdfs:domain](http://www.w3.org/TR/rdf-schema/#ch_range) and [rdfs:range](http://www.w3.org/TR/rdf-schema/#ch_domain) in inno, you can notice that most properties it defines don't set any rdfs:range and on illustration it shows as 'linking to' owl:Thing. Some of properties on the other hand have defined rdfs:range. In practice both rdfs:domain and rdfs:range don't _limit_ what you can use but rather _cause particular inferences_. Let's use example where we **assert** triples:

``` json
{
  "@context": {
    "schema": "http://schema.org/",
    "inno": "http://purl.org/innovation/ns#",
    "ex": "http://example.net/"
  },
  "@id": "https://github.com/bhaugen/valuenetwork",
  "@type": "schema:Code",
  "schema:name": "valuenetwork",
  "inno:hasBenefit": {
    "@id": "ex:vas",
    "@type": "ex:AccountingSystem",
    "schema:name": "value accounting system"
  }
}
```

Now when you run reasoner supporting RDFS, it will **infer** 2 extra triples

``` ttl
<https://github.com/bhaugen/valuenetwork> rdf:type inno:Innovation .
ex:vas rdf:type inno:Benefit .
```

resulting in:

``` json
{
  "@context": {
    "schema": "http://schema.org/",
    "inno": "http://purl.org/innovation/ns#",
    "ex": "http://example.net/"
  },
  "@id": "https://github.com/bhaugen/valuenetwork",
  "@type": ["schema:Code", "inno:Innovation"],
  "schema:name": "valuenetwork",
  "inno:hasBenefit": {
    "@id": "ex:vas",
    "@type": ["ex:AccountingSystem", "inno:Benefit"],
    "schema:name": "value accounting system"
  }
}
```

So 'connecting to Thing' or defining no rdfs:domain or rdfs:range, in practice means: "You can use this property (predicate) with subject and object of any rdf:type, and reasoners will not infer any additional triples".

**Comment by bhaugen** [comment]
I have not yet read the Working Ontologist, nor gotten deep into the current state of semantic web practices, so I should probably not speak of such things so casually. I tend to look at ontology by analogy with object models, which is probably wrong.

Our plan is to finish (roughly) our current version of the NRP software and then refocus on the next stage, which may mean a lot more emphasis on the Open Apps Ecosystem, which will include reading that book. Probably early next year.

Even after I read the book, though, I do not expect instant deep understanding.

But even so, don't you think it would be possible to narrow "used by" a bit more specifically than "Thing"? Or am I still missing something important?

**Comment by elf-pavlik** [comment]
If you would add rdfs:range to _inno:usedBy_ what rdfs:Class you would see helpful there?
Once again it would not _limit_ what you can use as value for this property, it would just **infer** that given [ a rdfs:Resource] has this rdfs:Class **also** as its rdf:type. Where everything can have any number of types which differs quite a lot from use of classes in most Object Oriented programming languages.

To make it more interesting schema.org doesn't actually use rdfs:domain and rdfs:range but [schema:domainIncludes](http://schema.org/domainIncludes) and [schema:rangeIncludes](http://schema.org/rangeIncludes) which makes it even more _loose_ and to my understanding pretty much serves as just sort of a cue for developers since it doesn't cause any **inferences**

**Comment by bhaugen** [comment]
Thanks for the followup, and your continued gentle prodding. I don't have an immediate answer to "what rdfs:Class you would see helpful there?", but this whole conversation is helpful as pointers to what I don't yet understand. 

I'm going leave inno here for now and may come back later when I think I understand better.

We try not to innovate, by the way. We try to build on stuff that other people have done. 

And we are not yet sure what benefit our software provides; it's part of some evolution. We are sure it is transitional, we hope to something better, but that's the best it can do.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
