### ISSUE TITLE
How is this being used?

### ISSUE THREAD

**Issue by pmackay** [valueflows/forum.valueflo.ws#10]
Would it be possible to add some info in the README describing how this vocab is or is intended to be used and where? Just for some useful context :)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/10.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
