### ISSUE TITLE
Fan-in fan-out recipe shapes

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#104]
In our NRP software (one of the proofs of concept of ValueFlows) we had two different types of recipes:
* manufacturing recipes, which assembled components into finished products, and
* workflow recipes, which transformed the same resource through a series of stages until it was finished.

Here's a [slide deck about recipes in NRP](https://speakerdeck.com/mikorizal/5-nrp-recipe-concepts-and-tutorial).

Manufacturing recipes tend to be fan-in: where many feeder processes condense into fewer process at each stage, usually culminating in a final assembly process.

Workflow recipes tend to be linear: a chain of processes. 

A typical example of a workflow recipe is translation, where some source material goes through stages like translate->edit->format->publish.

However, it is also common for translation processes to go like this:
create source material->edit->translate, where the translation fans out into many different languages (English, French, Spanish, Italian, German, Greek, Russian, Chinese, Kurdish, etc etc etc.

Our NRP recipes could handle fan-in and linear shapes very well, but did not handle fan-out.  We now have some examples of fan-outs for translations, and will fake it in the existing code base for awhile, but would like to figure out in ValueFlows how these should really be handled.

All ideas are welcome.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/104.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
