### ISSUE TITLE
Contexts for events

### ISSUE THREAD

**Issue by pmackay** [valueflows/forum.valueflo.ws#105]
Just thinking about how to filter a collection `EconomicEvent` records and wondering if a *context* could be defined/considered that could represent:

* a platform, such as Freecycle
* a place, such as a library
* etc

This seems similar to the context property of an `AgentRelationship` I think? 

An alternative name might be *channel*? *Platform* seems too specific - it works for Freecycle but not a library. 

Any thoughts on this @fosterlynn @bhaugen @elf-pavlik ?

(PS. Great progress on VF recently :-) )

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/105.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
