### ISSUE TITLE
minimal bottom-up P2P  economic system using ValueFlows

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#106]
Early draft, open for comments.
https://docs.google.com/document/d/1fNcmyzol72FctBbF3Nh8gLoRj6UbL9CnqLM2F7iuF2o/edit?usp=sharing

I called out @gcassel earlier because his work is also prominently mentioned.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/106.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
