### ISSUE TITLE
Any new spiral app news?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#107]
As in https://github.com/valueflows/valueflows/wiki/ValueFlows-spiral-apps

@elf-pavlik any new use cases, learnings, or VF-related code experiments in Vientos?

@pmackay - anything new from the circular economy arena?

@djodjoni - anything new happening with food apps?

@almereyda - anything new and VF-related from TransforMap?

Or anybody else? I could be forgetting someone...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/107.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
