### ISSUE TITLE
Mapping of VF to "traditional" ERP data

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#109]
This is a place to document a discussion we are having with Scuttlebutt people who are interested in working on a Scuttlebutt related implementation of economic activities, specifically coming from manufacturing and supply chain perspectives.  This will keep the documentation in one place, and maybe be useful to others.  More to come soon....

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/109.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
