### ISSUE TITLE
Practical uses of the linked data publishing format?

### ISSUE THREAD

**Issue by xekoukou** [valueflows/forum.valueflo.ws#11]
@bhaugen started a nice precedent in which we specify some simple problems and then check whether a specific implementation solves them.

In this context, I would like to ask the linked data experts ( @bshambaugh ) which problems does the linked data publishing format solve?

I know the general idea between the linked data format. I want a few examples how it would be used with the ovn model or any model you see fit. 

It seems to me that it can be used for data discovery and data traversal. Would you give a very specific example?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/11.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
