### ISSUE TITLE
Common process methods

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#110]
A question came up when Lynn and I were discussing recipes about process classifications. I said a lot of common processes exist that are independent of specific recipes, but have their own descriptions and techniques that are common to all of the recipes they might be used in. And I promised to look them up. 

This is similar to taxonomies of resource classifications, as in agrovoc.

Here are some lists of common processes, methods, and techniques:
* [in manufacturing](https://en.wikipedia.org/wiki/List_of_manufacturing_processes)
* [cooking](https://en.wikipedia.org/wiki/List_of_cooking_techniques)
* [circular economy](https://github.com/valueflows/valueflows/issues/96)

Depending on your familiarity with the methods specified in a particular recipe, it might be good to have a reference to an extended description of how to do it.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/110.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
