### ISSUE TITLE
What are the standard methods for alternate names for concepts?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#111]
I'm running into situations where people can understand the goals and even the concepts and relationships of VF but don't like the names for the concepts, and have other names that they would prefer in their community or domain. This is not aboout translations into other languages, it is about alternate names in the same language.

Is this the best way to accomplish that? Or some other way?
https://www.w3.org/TR/skos-reference/#L1606

**Comment by elf-pavlik** [comment]
If they use JSON-LD they can define aliases in the `@context` https://www.w3.org/TR/json-ld/#the-context

If they use something else, they can do whatever they want in the code but may need some kind of compatibility layer that would map their bespoke terminology to standard VF terms. Again in many cases things may not map 1-to-1 and mapping a domain specific construct may involve more than one VF primitive.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/111.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
