### ISSUE TITLE
Connect with the »Resource Based Economy — Center for Resource Management«

### ISSUE THREAD

**Issue by eMPee584** [valueflows/forum.valueflo.ws#113]
https://www.resourcebasedeconomy.org/center-for-resource-management
Common mission: system for clever transnational resource stream management.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/113.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
