### ISSUE TITLE
ActivityPub / ActivitySteams intersect ValueFlows / Open App Ecosystem

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#114]
This is a reference issue sort of on the fringe of VF, but I'm posting here instead of link dumps because there may be some vocabulary discussions spawned by this effort.  And because I know @elf-pavlik was involved to some degree with [ActivityPub](https://www.w3.org/TR/activitypub/), connected to the W3C Social Community Group.  And so might have useful insights on this.

Background: Several of us have been involved with the Open App Ecosystem effort for some years, both in [this loomio discussion](https://www.loomio.org/g/exAKrBUp/open-app-ecosystem) and more recently with groups who are interested in implementing some of these concepts, such as the [Mutual Aid Network](http://www.mutualaidnetwork.org/), and some people in FairCoop.  We always have seen VF as providing the economic vocabulary for these efforts, and it is already used in [parts of FairCoop](https://docs.opencoopecosystem.net/).

Recently a small group of us started looking into ActivityPub as potentially useful for providing decentralized communications / messaging infrastructure for interoperating apps, and perhaps more importantly the agents who form economic networks, in additional to social networks.  Also ActivityPub uses the ActivityStreams vocabulary, which we looked into when we began VF and which has some synergy with it.  ActivityPub is a spec; there are some implementations, such as Mastodon, an example of which is https://social.coop/about.

Here are some preliminary thoughts about how this might work cleanly, including with VF:  https://cryptpad.fr/pad/#/2/pad/edit/-R31XM73IlUVtp-Lpk6nCVL-/.  Much more work is needed, as well as a pilot, which we possibly can start with Mutual Aid Networks.

Feedback is welcome!

Or if anyone wants to work on it, give a shout!

**Comment by almereyda** [comment]
Hi @bhaugen thanks for the heads up. I am including @y0va who is the other developer in this regard and who :heart: valueflo.ws!

Right now we will only produce a frontend client with a budgeting application on top of an LDP data store. Don't know yet how ActivityPub fits in here right now. We could maybe imagine something like sending *change requests* to budgets or budget lines?

We now have few high level user stories available:

- https://lab.allmende.io/solidbase/solidbase/issues/16
- https://lab.allmende.io/solidbase/solidbase/issues/17
- https://lab.allmende.io/solidbase/solidbase/issues/18

**Comment by bhaugen** [comment]
@almereyda @y0va
> Don't know yet how ActivityPub fits in here right now.

Maybe participatory budgeting? 

And, got any idea what a budget line looks like? I see ``` label, description and language```, but what else?

And, budgeting for what, whom, why?

Don't mean to ask for a ton of info. Pick and choose what to respond to if anything. I'm just being curious, not needy.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/114.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
