### ISSUE TITLE
How would you like ValueFlows to be cited?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#115]
...because it is starting to happen. See https://github.com/valueflows/valueflows/issues/269#issuecomment-395957283

The tendency is to pick out some individuals, often inaccurately as in that case, because they can't handle reality.

Since I know we have at least one contributor who is uncomfortable with ValueFlows being an organization, I suggested the ValueFlows unorganization. Good enough? Got better ideas?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/115.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
