### ISSUE TITLE
json-LD problems reported by ActivityPub devs

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#117]
https://iscute.moe/notice/1715743

Let me know if you can't see this and I will post the contents here.

Does anybody know if these are real or imaginary problems? Or if real, how to work around them?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/117.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
