### ISSUE TITLE
Moinho Mesh project - VF mapping

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#118]
I'm moving some ongoing discussion here so other VF participants can chime in if they like.  This is a project in Brazil being done by @Luandro using ssb and dat, to wire a village for internet and social / economic interaction.  He wants to use VF for this.  And there is one other person wanting to use VF with ssb (for processes), so these projects will be the start of implementing VF standard message types in ssb.

The first user story is to get broadband installed.  I'll include a picture from Luandro when I resolve a problem I'm having with github. :(

**Comment by elf-pavlik** [comment]
Any updates on this exploration? Actually last few months we also use broadband connection installed in a small town 5km from here. We've setup a wireless bridge and made it available here to couple other bungalows.

In setup above, why do you need a 'Share'? People can't just *use* the broadband connection or receive a *service*? 
Our setup doesn't require us to distribute expense related to electricity used by equipment running 24/7 but I think it also could play role in this scenario.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/118.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
