### ISSUE TITLE
active non-activity

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#12]
a use case that's been brought up for [Cobudget](http://cobudget.co) is being able to disambiguate intentional saving and lack of engagement.

> i find ... lack of clarity around whether people are not engaging because they’d rather save their money or because they’re lazy

i see this as being able to signal an active decision to not do anything. not sure how we should approach this though, curious what others think.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/12.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
