### ISSUE TITLE
Playing with holochain

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#121]
![screenshot from 2018-04-12 16-37-41](https://user-images.githubusercontent.com/117439/38705893-c8e99466-3e70-11e8-90de-6fe48d6ddda8.png)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/121.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
