### ISSUE TITLE
Holo Demo Scenario

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#125]
@sqykly is working on a "good first demo" in Holochain.  Here is the rough scenario:

A cast of agents:
-- Al, who runs "Al's Apple Farm".
-- Bea, who runs "Bea's Beans".
-- Chloe, who runs "Cloe's Coffee".

The story:
-- Al has picked 100 apples.
-- Bea has gathered 2 kg of beans.
-- Chloe owns 300 mL of coffee (beginning balance).
-- At that exact moment, Al arrives with 3 apples. He gives them to Chloe, Chloe receives them.
-- In exchange, Chloe gives Al a 300 mL cup of coffee. Al receives it.
-- Chloe consumes 3 apples to bake 1 turnover.
-- Bea wants the 1 turnover in exchange for 1/2 kg of her beans. See above for how that works.
-- Chloe consumes those beans to brew 1000 mL of coffee

The idea for the demo is to enter the data at each step and be able to see inventory (or a primitive balance sheet) for each agent at each step.

I'd like to define this out in more detail here. Partly this is to contribute to the current discussions on transfers.  Partly this is to better define this scenario in VF terms with expected outputs.

#### Al has picked 100 apples.
Process:
-- id: 123
-- name: Pick apples
EconomicEvent:
-- id: 1
-- action: produce
-- outputOf: Process 123
-- provider: Al
-- receiver: Al
-- affectedQuantity:
---- numericValue: 100
---- unit: Count
-- observedTime: 2018-10-10
-- affects: EconomicResource 1
EconomicResource:
-- id: 1
-- resourceClassifiedAs: Apple
-- currentQuantity: 
---- numericValue: 100
---- unit: Count

#### Bea has gathered 2 kg of beans.
Process:
-- id: 456
-- name: Gather coffee beans
EconomicEvent:
-- id: 5
-- action: produce
-- outputOf: Process 456
-- provider: Bea
-- receiver: Bea
-- affectedQuantity:
---- numericValue: 2
---- unit: kg
-- observedTime: 2018-11-11
-- affects: EconomicResource 5
EconomicResource:
-- id: 5
-- resourceClassifiedAs: Coffee beans
-- currentQuantity: 
---- numericValue: 2
---- unit: kg

#### Chloe owns 300 mL of coffee (beginning balance).
EconomicEvent:
-- id: 10
-- action: adjust
-- provider: Cloe
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 300
---- unit: mL
-- observedTime: 2018-11-20
-- affects: EconomicResource 10
EconomicResource:
-- id: 10
-- resourceClassifiedAs: Coffee
-- currentQuantity: 
---- numericValue: 300
---- unit: mL

#### Inventory
Al: 100 Apple
Bea: 2 kg Coffee beans
Cloe: 300 mL Coffee

#### Al arrives with 3 apples. He gives them to Chloe, Chloe receives them.
Transfer:
-- id: 2
EconomicEvent:
-- id: 30
-- action: give
-- provider: Al
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 3
---- unit: Count
-- observedTime: 2018-11-20
-- affects: EconomicResource 1 (currentQuantity now 97)
-- inputOf: Transfer 2
EconomicEvent:
-- id: 31
-- action: receive
-- provider: Al
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 3
---- unit: Count
-- observedTime: 2018-11-20
-- affects: EconomicResource 30
-- outputOf: Transfer 2
EconomicResource:
-- id: 30
-- resourceClassifiedAs: Apple
-- currentQuantity: 
---- numericValue: 3
---- unit: Count

#### Inventory
Al: 97 Apple
Bea: 2 kg Coffee beans
Cloe: 300 mL Coffee, 3 Apple

#### Chloe gives Al a 300 mL cup of coffee. Al receives it.
Transfer:
-- id: 3
EconomicEvent:
-- id: 33
-- action: give
-- provider: Cloe
-- receiver: Al
-- affectedQuantity:
---- numericValue: 300
---- unit: mL
-- observedTime: 2018-11-20
-- affects: EconomicResource 10 (currentQuantity now 0)
-- inputOf: Transfer 3
EconomicEvent:
-- id: 34
-- action: receive
-- provider: Cloe
-- receiver: Al
-- affectedQuantity:
---- numericValue: 300
---- unit: mL
-- observedTime: 2018-11-20
-- affects: EconomicResource 34
-- outputOf: Transfer 3
EconomicResource:
-- id: 34
-- resourceClassifiedAs: Coffee
-- currentQuantity: 
---- numericValue: 300
---- unit: mL

#### Inventory
Al: 97 Apple, 300 mL Coffee
Bea: 2 kg Coffee beans
Cloe: 0 mL Coffee, 3 Apple

#### Chloe consumes 3 apples to bake 1 turnover
Process:
-- id: 789
-- name: Bake turnover
EconomicEvent:
-- id: 50
-- action: consume
-- inputOf: Process 789
-- provider: Cloe
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 3
---- unit: Count
-- observedTime: 2018-12-01
-- affects: EconomicResource 30 (currentQuantity now 0)
EconomicEvent:
-- id: 51
-- action: produce
-- outputOf: Process 789
-- provider: Cloe
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 1
---- unit: Count
-- observedTime: 2018-12-01
-- affects: EconomicResource 55
EconomicResource:
-- id: 55
-- resourceClassifiedAs: Apple turnover
-- currentQuantity: 
---- numericValue: 1
---- unit: Count

#### Inventory
Al: 97 Apple, 300 mL Coffee
Bea: 2 kg Coffee beans
Cloe: 0 mL Coffee, 0 Apple, 1 Apple turnover

#### Cloe gives Bea the 1 turnover
Transfer:
-- id: 5
EconomicEvent:
-- id: 60
-- action: give
-- provider: Cloe
-- receiver: Bea
-- affectedQuantity:
---- numericValue: 1
---- unit: Count
-- observedTime: 2018-12-02
-- affects: EconomicResource 55 (currentQuantity now 0)
-- inputOf: Transfer 5
EconomicEvent:
-- id: 61
-- action: receive
-- provider: Cloe
-- receiver: Bea
-- affectedQuantity:
---- numericValue: 1
---- unit: Count
-- observedTime: 2018-12-02
-- affects: EconomicResource 60
-- outputOf: Transfer 5
EconomicResource:
-- id: 60
-- resourceClassifiedAs: Apple turnover
-- currentQuantity: 
---- numericValue: 1
---- unit: Count

#### Bea gives Cloe 1/2 kg of her beans
Transfer:
-- id: 5
EconomicEvent:
-- id: 60
-- action: give
-- provider: Bea
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: .5
---- unit: kg
-- observedTime: 2018-12-02
-- affects: EconomicResource 5 (currentQuantity now 1.5)
-- inputOf: Transfer 5
EconomicEvent:
-- id: 61
-- action: receive
-- provider: Cloe
-- receiver: Bea
-- affectedQuantity:
---- numericValue: 1
---- unit: Count
-- observedTime: 2018-12-02
-- affects: EconomicResource 60
-- outputOf: Transfer 5
EconomicResource:
-- id: 60
-- resourceClassifiedAs: Coffee beans
-- currentQuantity: 
---- numericValue: .5
---- unit: kg

#### Inventory
Al: 97 Apple, 300 mL Coffee
Bea: 1.5 kg Coffee beans, 1 Apple turnover
Cloe: 0 mL Coffee, 0 Apple, 0 Apple turnover, .5 kg Coffee beans

#### Chloe consumes those beans to brew 1000 mL of coffee
Process:
-- id: 987
-- name: Brew coffee
EconomicEvent:
-- id: 70
-- action: consume
-- inputOf: Process 987
-- provider: Cloe
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: .5
---- unit: kg
-- observedTime: 2018-12-15
-- affects: EconomicResource 60 (currentQuantity now 0)
EconomicEvent:
-- id: 71
-- action: produce
-- outputOf: Process 987
-- provider: Cloe
-- receiver: Cloe
-- affectedQuantity:
---- numericValue: 1000
---- unit: mL
-- observedTime: 2018-12-15
-- affects: EconomicResource 10 (currentQuantity now 1000)

#### Inventory
Al: 97 Apple, 300 mL Coffee
Bea: 1.5 kg Coffee beans, 1 Apple turnover
Cloe: 1000 mL Coffee, 0 Apple, 0 Apple turnover, 0 kg Coffee beans

**Comment by fosterlynn** [comment]
>> -- action: adjust

>I would suggest to start with already existing vf:increment and later make PR which would propose different way to increment and decrement and explaining need for it.

I forgot we don't have `adjust`.  I'll make a PR.  vf:increment won't work, it is not always an increment.  The 2 use cases are beginning balances and inventory counts that need to override what the system is showing.

>Lynn also wants to do a mini incoming value flows traversal,

Yes, that is my hope.  But also I felt it was important to have the value flows in the code and data examples for this demo because there will be devs and others interested in the detail of how REA/VF works.  Processes and transfers are needed for that, as well as to just make it clear what is actually going on.

**Comment by bhaugen** [comment]
> But I hope we can agree to not throw out the whole concept.

The concept is required.

P.S. Sensorica uses custody all the time, so we need that concept, too.

**Comment by elf-pavlik** [comment]
@sqykly I've just published first version of track-trace algorithms implemented in typescript:
https://github.com/valueflows/vf-track-trace.ts#readme

It relies on asynchronous [RDFJS Source interface](http://rdf.js.org/#source-interface) which one could very likely implement over Holochain. It provides asynchronous iterator for tracking and tracking. Feedback welcome directly in `vf-track-trace.ts` repository :ear:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/125.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
