### ISSUE TITLE
good challenge for newcomers to ValueFlows

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#126]
https://github.com/valueflows/valueflows/blob/master/use-cases/industrial-vs-permaculture-tea.md

The permaculture cup of tea should not be too difficult...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/126.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
