### ISSUE TITLE
savings pools example

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#13]
@joshuavial was kind enough to share [a work in progress specification for a savings pool system](https://docs.google.com/document/d/1HEVnbs1Uajef-_YSgnHbtlcnaUXdu-L6-x5KGaqz8yE/edit?usp=sharing). i think this is another great example to work with to test that our Value Network vocab here can support what is being described in the spec.

my initial thoughts are that we can describe the various *Tokens as Resources and do most of the value flow as Exchange events. i'm unsure about the put options, although it seems like they could be just another Resource, but maybe Commitments fit in somewhere.

@bhaugen @fosterlynn, do y'all have any initial thoughts on this?

**Comment by bhaugen** [comment]
I'm not sure I understand Joshua's use case in detail, so I'll comment on vocab and blockchains.

Short version:
- Vocab:
  - Short term advice: study [FIBO](http://www.google.com/url?q=http%3A%2F%2Fwww.edmcouncil.org%2Fsemanticsrepository%2Findex.html&sa=D&sntz=1&usg=AFQjCNGk5tej8F5mfg8ohwnxAPsEVSgcCA) and use what you like. And look at Christian Scheller's Put model in the document linked below.
  - Longer term: let's recast what we like from FIBO in simpler REA terms as much as possible. Conditional commitments will be one key component, which will require deciphering [this paper about Compositional specification of commercial contracts](http://www.itu.dk/people/elsborg/sttt06.pdf). 
- Blockchains:
  - I am deeply skeptical. 
    - Increasingly expensive proof of work
    - Exploding size requirements for nodes [apparently somewhat mitigated in Ethereum]
    - Leading to monopolies [ironically for a bunch of libertarians who wanted decentralism]
  - I could be totally wrong.

See [my notes](https://docs.google.com/document/d/17QCJ5TstkZgwDkAz2CQmRbRRakfaFf9wMcDBzSfDooI/edit?usp=sharing) for the very long version.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/13.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
