### ISSUE TITLE
Revisiting Conversations for Action

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#131]
We've discussed this topic several times before in ValueFlows and surrounding circles, but we are now ready to start implementing it in [HoloREA](https://github.com/holo-rea) with some real user groups, so I am doing some deeper study and will start reporting it in this thread. My goal is to prepare for use.

Feel free to comment, ask questions, raise problems, suggest improvements.

**Comment by bhaugen** [comment]
### Introduction

[Conversation for Action](https://valueflo.ws/introduction/cfa.html) is a human protocol for peer-to-peer coordination by means of structured conversations to arrive at commitments to take some agreed-upon actions.

Those conversations are not just nice chats, they are intended to coordinate processes and resource flows. And the processes and resource flows will continue to have more conversations for action embedded within them for ongoing coordination.

The conversations are conducted by means of vocabularies which would include the usual ValueFlows statements but they are also [speech acts](https://en.wikipedia.org/wiki/Speech_act) which might suggest some additions to the VF vocabulary to denote types of utterances.

### History
> The reflections behind “Conversations for Action” date back to my term in the Allende government in Chile, where the question of communication for getting work done first came to me. I later developed the subject in my dissertation, “Management and Communication in the Office of the Future,” at the University of California, Berkeley.

> At the core of all of the essays is my understanding of language as the fundamental characteristic of what makes us human.

> Years later, with colleagues in organizations I led, I developed a structure for analyzing an enterprise as a network of commitments.  The basic molecule is what we called the "Conversation for Action", also referred to as the "Basic Action Workflow".

> For many years, many of these documents lived only in the hands of the many practioners who studied with me. Some were available in courses or for clients, and some were developed only for internal training. Upon the request of several of these practioners and former clients, I have decided to make these available in the form of a book. I look forward to hearing all of those who work with the conversations for action framework or networks of commitment/commitment based management approach to management and learning more about how you are utilizing the approach to make an impact in your work.

> Sincerely, Fernando Flores, Berkeley CA.

- from http://conversationsforaction.com/history

**Comment by bhaugen** [comment]
### Speech acts for conversations for action:
* propose – someone proposes to create, change, or cancel an Intent
* accept – someone accepts a previous proposal
* reject – someone rejects a previous proposal
* counter - someone makes a counter-proposal
* declare – someone unilaterally creates, changes, or cancels an Intent
* query – someone asks for information
* reply – someone replies to a previous query
* assert – someone makes a statement about one or several Intents 
* withdraw - someone leaves an unfinished conversation
* renege - someone asserts that they will not fulfill a previously-accepted commitment

From http://www.itu.dk/people/kasper/REA2004/pospapers/PrasadJayaweera.pdf - source of the state machine diagram we use in [the VF intro section on CfA](https://valueflo.ws/introduction/cfa.html).

![CfA_state_machine big](https://user-images.githubusercontent.com/117439/56866852-dffd0e80-69a3-11e9-8b06-a560786aa545.png)

**Comment by bhaugen** [comment]
### Conversations for action in context (part 1):
Procurement loops from http://denninginstitute.com/modules/workflow/DOCUMENTS/Denning-Abstract1.html
![procurement CfA loops](http://denninginstitute.com/modules/workflow/IMAGES/proc1.gif)

**Comment by bhaugen** [comment]
### More CfA explanation:

> We can plot the basic course of a conversation in a simple diagram like that of Figure 5.1, in which each circle represents a possible state of the conversation and the lines represent speech acts. This is not a model of the mental state of a speaker or hearer, but shows the conversation as a ‘dance.’ [p. 64]

![1986_Winograd_Flores_Figure_5.1.jpg](http://coevolving.com/blogs/wp-content/uploads/2008/05/1986_winograd_flores_figure_51.jpg)
> Figure 5.1: The basic conversation for action

> The lines indicate actions that ran be taken by the initial speaker (A) and hearer (B). The initial action is a request from A to B, which specifies some conditions of satisfaction. Following such a request, there are precisely five alternatives:
* the hearer can accept the conditions (promising to satisfy them),
* can reject them, or
* can ask to negotiate a change in the conditions of satisfaction (counteroffer).
* The original speaker can also withdraw the request before a response, or
* can modify its condition. [p. 65, editorial paragraphing added]

> Each action in turn leads to a different state, with its own space of possibilities. In the ‘normal’ course of events, B at some point asserts to A that the conditions of satisfaction have been met (moving to the state labelled 4 in the figure).

> If A declares that he or she is satisfied, the conversation reaches a successful completion (state 5).
On the other hand, A may not interpret the situation in the same way and may declare that the conditions have not been met, returning the conversation to state 3.
In this state, either party may propose a change to the conditions of satisfaction, and in any state one or the other party may back out on the deal, moving to a state of completion in which one or the other can be held ‘liable’ (states 7 and 9).

From http://coevolving.com/blogs/index.php/archive/conversations-for-action-commitment-management-protocol/

**Comment by bhaugen** [comment]
### [More types of conversations:](https://prezi.com/fxauh7vx915c/4-types-of-conversation/)
* [Conversation for relationship](https://justinwise.co.uk/2013/10/16/speech-acts-3-conversations-for-relationship/)
* [Conversation for possibility](https://justinwise.co.uk/2013/10/17/speech-acts-4-conversations-for-possibility/)
* [Conversation for opportunity aka field narrowing](https://www.mediawiki.org/wiki/Good_meetings#Taxonomy) 
* [Conversation for clarification](https://justinwise.co.uk/2016/05/03/a-conversation-for-clarification/)
* [Conversation to collaborate](http://www.dubberly.com/models/conversation_collaborate.html)
* [Conversation for agreement](http://www.dubberly.com/models/conversation_agreement.html)

How many of these conversations are worth formalizing as state machines?. How many are worth naming, wrapping, and identifying in conversational flows? How many could be components of larger conversational patterns?

**Comment by bhaugen** [comment]
![CfA flows](https://user-images.githubusercontent.com/117439/56869035-7d663b80-69c0-11e9-856c-6f27ab8f5a67.png)

Conversations typically plan processes and negotiate exchanges (as well as appearing in many other situations).

**Comment by bhaugen** [comment]
Contract negotiation conversation, similar to CfA, from http://www.ebxml.org/specs/bpPATT.pdf:
![contract-negotiation](https://user-images.githubusercontent.com/117439/56869472-ef418380-69c6-11e9-9f43-2696e95367b8.png)

**Comment by bhaugen** [comment]
### [Language/Action Perspective on the Design of Cooperative Work](http://hci.stanford.edu/~winograd/papers/language-action.html)

Terry Winograd was Fernando Flores' partner in the work around Conversations for Action and the book they wrote together, [Computers and Cognition](https://books.google.com/books?id=2sRC8vcDYNEC&source=gbs_navlinks_s). One of his important papers on this set of topics is linked to the title of this comment. In it, he describes several examples in medical settings,and adds yet another type of conversation:
* Conversations for orientation
> When asked to comment on the systems analysis, the nurses felt that it did not capture the aspect of their activities that dealt with the total picture rather than with the specifics of particular medications and tests. The existing structure provides explicit routines to allow for open-ended conversation, such as the morning report, where One nurse is informing the other staff of the status, changes and performed activities of each patient during the last day and night. Informal exchanges among the nurses include both explicit CfAs and more general orienting discussion about the total picture. One form of orienting conversation is the telling of stories, whether in the direct line of work, or around the coffeepot. Orr (1986) describes the importance of relating war stories as part of technical training. One has only to spend a short time in the company of medical workers to realize how prevalent this activity is.

And he notes that "the conversational analysis includes not only those immediately visible, but also the larger web of conversations in which they are situated".

**Comment by bhaugen** [comment]
Simpler diagram:
![basic CfA](http://pluralisticnetworks.com/img/loop_baw.jpg)
from http://pluralisticnetworks.com/

**Comment by bhaugen** [comment]
> ### [More types of conversations:](https://prezi.com/fxauh7vx915c/4-types-of-conversation/)
> * [Conversation for relationship](https://justinwise.co.uk/2013/10/16/speech-acts-3-conversations-for-relationship/)
> * [Conversation for possibility](https://justinwise.co.uk/2013/10/17/speech-acts-4-conversations-for-possibility/)
> * [Conversation for opportunity aka field narrowing](https://www.mediawiki.org/wiki/Good_meetings#Taxonomy)
> * [Conversation for clarification](https://justinwise.co.uk/2016/05/03/a-conversation-for-clarification/)
> * [Conversation to collaborate](http://www.dubberly.com/models/conversation_collaborate.html)
> * [Conversation for agreement](http://www.dubberly.com/models/conversation_agreement.html)

Some of us are now engaged in a series of conversations with different projects who interested in what @pospi calls [the REA community of practice](https://github.com/holo-rea/ecosystem/wiki/Coordinating-the-REA-community-of-practise). Seems like a good name to me.

So each of these conversations starts with some expressions of intent, which are not yet intents to do much but learn, maybe starting with a Conversation for Relationship and moving on to Conversations for Possibility, trying to decide if they want to progress to Conversations for Collaboration.

The arrows between the conversations in this diagram are filled with intents to move on to the next conversation. Or not.

![Conversational flows](https://user-images.githubusercontent.com/117439/57140041-72265d80-6d7c-11e9-9414-11e102ed4cc0.png)

If only we had some software that could keep track of all of these conversations and then keep tracking into the ensuing actions..............

**Comment by mike-hales** [comment]
@bhaugen  20 years back there was controversy in the CSCW field around the speech act model. Anthropologists felt it was flaky or even detrimental, cyber-folks thought it was hunky dory. I don't recall the ins & outs, but my inclination is generally to go with anthros rather than cyberneticists. My colleague Lucy Suchman at Xerox PARC was a main antagonist, in CSCW Journal, in an exchange with Winograd. I don't recall how much of the argument was about The Coordinator as a cooperation app, and how much was about the basic framing of human interaction, and intrinsic limitations of this - probably the latter. RU aware of this stuff? I could swot up on this if necessary, though I was never very fluent in the issues.

I guess I wonder why a formalisation of agreeing (a state machine) is needed . . as distinct from a free-form human-to-human communication-media layer in which agreements are arrived at, resulting in pressing a <Go> button with an appended service agreement, maybe built from boiler plate? Is it to do with the force that the agreements have? Or is it to do with having options baked-into (and limited by) the software? Should I do my homework on this and read something more above, or in another thread? I may be out of my depth here, in terms of the amount of work it may take, to reason this out. So treat this as a query rather than a challenge.

Full disclosure . . I'm pretty sceptical about the Viable Systems Model that Flores, Varela, Beer & co elaborated in Chile. In the 60s is was built by Beer from an Erector-kit of cyber-components and Bayesian statistics, looked plausible as a model of brain, and Beer sold it to corporates and Presidents alike. Today, with theory of mind way more developed, I'd say it was flaky as a model of mind; and it's mind not brain that is the appropriate analogy. As an algorithimic machine, there are issues, not well attended to I think, regarding the part that an algorithmic machine can properly play in actual social practice and informed choice-making. I'm aware that there are real fans of VSM in the coop world. I also suspect that it serves as a metaphor for geeky cooperators to use in conversation, rather than anybody seriously implementing it as a working machine whose outputs have direct wired-in operational impacts. So . . scepticism here about the cyber agenda. IMO cybernetics applies to material systems, not cultural ones (and of course, everything is a material system, so there's potentially some scope in any practice). In VF the cyber-formalisation orientation may not go any further than the speech act model? But just registering an anthropologist-facilitator's general perspective.

**Comment by bhaugen** [comment]
I love most of Lucy Suchman's work that I know about. I also am probably the main proponent of Flores's work (mostly the conversations, not the rest) in VF. And I like speech acts, too. What did Walt Whitman say about being inconsistent?

I am, however, also skeptical about VSM and analogies of systems with human bodies. 

My reasons for wanting explicit agreements and the whole Conversation for Action model include:
* It is often really necessary to be able to track the whole provenance of economic resources. Think mad cows. Explicit agreements about what happened are part of that.
* The introduction of money changes social and cultural dynamics:
* take-backs happen all the time in online economic groups;
* FairCoop (for only one example) has spent months arguing about whether they did or did not agree to something (all having to do with money, one way or another). 
* Plus, CfA includes an explicit stage of evaluating how that agreement and fulfillment went.
* Beyond the social-economic dynamics, there's the difficulties of communication securely using unreliable devices over an unreliable network, which get much much worse with distributed systems, which we want to develop.

So @mike-hales did that all make sense? You are welcome to quote Lucy Suchman at me....;-)

**Comment by bhaugen** [comment]
P.S. @mike-hales we want the economic networks to be merged with the social networks, so the social interactions and the economic interactions get intermingled and can reference each other. So the participants in a formal agreement will have lots of opportunities for informal chat. It's not like I think the informal chats are unimportant.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/131.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
