### ISSUE TITLE
Multi-agent conversations

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#132]
@elf-pavlik I unearthed an old paper I co-wrote in 2002 when I first started working with Choreology, a London startup that is now dead. But they had the best thinking about distributed transactions that I knew of, which is why I went to work for them: to learn those techniques.

The first thing I worked on was a method of handling multi-party distributed transactions, because neither CfA nor any of the transaction processors of that time (except the [Paxos family](https://en.wikipedia.org/wiki/Paxos_(computer_science))) could handle them, and Paxos is a bear to implement.

This is a paper me and Tony Fletcher wrote, but a couple of other Choreology people were in on the discussions. What we decided at that time was it was better, if possible, to separate multi-party transactions into pairs of two-party transactions and coordinate the pairs for the desired overall result. 

I'm dropping this here now to see if it makes sense to you, and it you think it could possibly handle your multi-lateral exchanges.
https://drive.google.com/open?id=1NkAY4QhI1ra2vjFvY1GzPPJXvYWJDgxg
Here's a later paper that build on that one:
http://www.cs.rug.nl/~aiellom/publications/refs07.pdf

Anyway, get the basic idea, don't get distracted by the chickens or obsess about the details. The details of your use case will be different. (@elf-pavlik I assume that is obvious to you, but this is a public forum and I thought I should add that...)

**Comment by bhaugen** [comment]
Short version of that paper:
A transaction coordinator conducts a set of two-agent transactions and if all of those are committable, commits the multi-agent transaction. If any of the two-agent transactions fail, so does the multi-agent transaction.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/132.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
