### ISSUE TITLE
Link dumps 2020

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#134]
I don't think @almereyda has created a new link dumps thread for 2020 so here it is.

**Comment by bhaugen** [comment]
https://emmc.info/emmo-info/
Lotta good general intro to ontologies.
See also https://emmc.eu/

Hat tip to @sebastienh  in https://github.com/HajoRijgersberg/OM/issues/33#issuecomment-611892604

**Comment by bhaugen** [comment]
More on ontologies vs taxonomies 
https://anticapitalist.party/@syndikalista/103979453800671522

**Comment by bhaugen** [comment]
ValueFlows videos:

Lynn telling the pie story to Thomas Miller:
https://youtu.be/SWvPM9Uza_w

Lynn and I doing a guest lecture for Bill McCarthy's accounting class:
http://mikorizal.org/McCarthy_Class_Guest_Lecture_on_ValueFlows.mp4
...featuring an embarrassing quantity of ums and uhs from me...

At the end, our comments on Kip Twitchell's predictions, with feedback from Kip and Erik Denna. See also https://github.com/valueflows/forum.valueflo.ws/issues/135

**Comment by bhaugen** [comment]
https://naturalcapitalproject.stanford.edu/software/invest
> ...a suite of models used to map and value the goods and services from nature that sustain and fulfill human life.  It helps explore how changes in ecosystems can lead to changes in the flows of many different benefits to people.

And they are hiring, if any of y'all want a job:
https://naturalcapitalproject.stanford.edu/who-we-are/open-positions

Hat tip Dante-Gabryell Monson (who doesn't seem to have a github id, but I'll thank him in email).

**Comment by bhaugen** [comment]
https://siderea.dreamwidth.org/1617582.html
> I want to hammer this home, and make sure you get the full import of this: a single, one-time persistent bump-up in customer demand plunges the system into wild boom-bust oscillations. Consistently. Consistently. Always.
>
> "A single one-time persistent bump-up in customer demand" is an accurate description of what just happened in the market for household supplies anywhere there's a stay-at-home order.
> 
> Every household now buying twice as much toilet paper because they are simply home twice as much and using twice as much. Every household now buying as much more food from grocery stores as they used to buy from restaurants they no longer patronize. Every household now buying sanitizers they didn't use to need in such quantity because they have to clean more things and more frequently.
> 
> These changes represent a single, one-time persistent bump-up in consumer demand for these things. Demand for certain consumer goods just went up, and will stay at that new heightened level, indefinitely.
> 
> We are in the Beer Game.
> 
> And what the Beer Game teaches us is that the supply chain will start showing massive fluctuations. There will be shortages and then gluts, in repeating cycles.
> 
> This is not because people are hoarding. This is not because of fickle consumer demand. This is not because of consumers doing anything wrong. Supply chains being massively disrupted doesn't require any of these things.

**Comment by bhaugen** [comment]
[Paxos vs Raft: Have we reached consensus on distributed consensus?](https://arxiv.org/pdf/2004.05074.pdf)
> Distributed consensus is a fundamental primitive for constructing fault-tolerant, strongly-consistent distributed systems. Though many distributed consensus algorithms have
been proposed, just two dominate production systems: Paxos,
the traditional, famously subtle, algorithm; and Raft, a more
recent algorithm positioned as a more understandable alternative to Paxos

These algorithms are useful for synchronizing agreement among the agents participating in a particular situation: for example, a transaction or conversation for action. 

They are not aimed at global consensus like a blockchain.

**Comment by almereyda** [comment]
In this direction, I recently liked the presentation of GossipSub by David Dias during the [Open Tech Will Save Us Meetup #1 at 59' ff.](https://youtu.be/APVp-20ATLk?t=3540), in which he shows how they achieve *eventual*, *lazy* consensus over time.

* [specs/pubsub/gossipsub at master · libp2p/specs](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub)
* [Gossipsub V1.1 at 'Open Tech Will Save Us' Virtual Event | Protocol Labs Research](https://research.protocol.ai/posts/202004-matrix-virtual-meetup-gossipsub/)

**Comment by bhaugen** [comment]
Springer is offering some free textbook downloads:
https://drive.google.com/file/d/19gqH8Z9UIC_3sDS4_cO75uMV15JDPsl3/view
I'm looking into [Supply Chain Management and Advanced Planning](https://link.springer.com/book/10.1007%2F978-3-642-55309-7) to see if there's anything really new since I was in that game in the 1990's.
Reading the [Advanced Planning chapter](https://link.springer.com/content/pdf/10.1007%2F978-3-642-55309-7_4.pdf).
Don't see anything really new, just a lot more use of optimization software, which, when I was in the game, was more of a problem than a solution. The optimization algorithms were brittle and would flail schedules around with every change of conditions, which was an operational nightmare.

But maybe it's getting better. They do talk about event-driven rescheduling, which could be done with smaller changes to the operational schedules.

**Comment by bhaugen** [comment]
FB announces its combo of social and (very limited) economic networking:
https://www.cnbc.com/2020/05/19/zuckerberg-announces-facebook-shops-e-commerce-for-businesses.html

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/134.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
