### ISSUE TITLE
Kip Twitchell's predictions

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#135]
Predictions as of April 2020

• Any currency is fundamentally transferrable credit, whether issued by a government or any other entity. The most effective type of transferable credit over time is that which is backed by integrity--the commitment of the person issuing the promissory note to repay--as the value of any other asset in the future will always be uncertain.
• Trustworthiness begets efficiencies, efficiencies not available in any other way. Its power is akin to that of intelligence and knowledge. Those who are trustworthy will continue to find ways to enhance the efficiencies from interacting with those also committed to trustworthiness and integrity.
• In the same way fundamental bookkeeping increases intelligence by accurately and understandably recording what has happened and projecting what will happen, trustworthiness and integrity increase efficiencies through community, sharing, specialization and mutual dependence. "Trustlessness," one of the Bitcoin blockchain goals, is a dead-end road.
• The forgotten knowledge embedded in our financial systems, including what a ledger is and how to improve it, can be recovered and enhanced, and the incredible efficiencies created by those who have gone before can be increased, and extended to perhaps billions of people, including the most simple and poorest merchants in the world, enabling access to knowledge through bookkeeping, at reduced costs through sharing, distributed by low-cost technologies.
• The resulting system will fundamentally be about organized, accurate, updatable, understandable, secure and accessible financial data. It will be broadly controlled by the owners of the data, their partners, both directly and speaking through their governments and other institutions. The change may be so radical it may upend the current concentration of capital.
• These changes will be abetted by the failure of trustworthiness and integrity in some existing financial and business institutions, and furthered by the courage, intelligence and caring of the many committed to integrity.

From https://drive.google.com/file/d/1cDtdicwRp42jy-kufnHwUbGueYZ3N0np/view
Presented at Bill McCarthy's class at Michigan State University:
https://ledgerlearning.com/2020/04/20/sharealedger-org-my-report-to-dr-bill-mccarthy-on-rea-progress/

@fosterlynn and I will comment on some of Kip's predictions in another McCarthy class on Wednesday April 22 at the end of our ValueFlows presentation.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/135.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
