### ISSUE TITLE
Exchanges in Recipes and plans from recipes

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#136]
@fosterlynn is preparing to add exchanges to recipes and thus to planning from recipes.

This is a good and necessary idea, but brings with it some interesting side issues. Here I'll ponder some of those issues.

In an economic network composed of more than one independent agent, can one agent make plans that will need to be executed by other independent agents?

An exchange transfers resources from one agent to another, so planning an exchange requires agreement on the plan among the various agents involved.

Let's say that the purpose of an exchange in a recipe is to specify and plan how Agent A will get some resources as inputs to a planned process. When a plan is generated from that recipe, the dependent demand explosion will stop at the demand for that input, which is the outer limits of Agent A's scope, and will generate an Intent (Request) for the required resources.

Can the recipe exchange specify that the request for the resources will  be sent to Agent B? Or broadcast to an intent-casting medium?

Recipes do not specify any Agents. They are assumed to be open recipes. 

Can the dependent demand explosion send a request to Agent B, or can the recipe and thereby the plan explosion continue in Agent B's scope, maybe planning the production and delivery of the required resources?

That would require some prior agreements between Agent B and Agent A, which might be configured by some event-condition-action loop like IFTTT (If This Then That). Those rules would be separate from the recipe, although they could reference it.

**Comment by bhaugen** [comment]
Related question: if a RecipeExchange is added to a recipe, is that the end of that branch of that recipe?

Or would it be valid to have a RecipeExchange and then continue to add more RecipeProcesses, etc? For example, creating a recipe that can traverse a whole supply chain? Or is that a bad idea?

**Comment by bhaugen** [comment]
More on the
> event-condition-action loop like IFTTT

...and other possible add-ons to recipes that could involve more agents in the generated plans.

If the triggering event is "new Intent to request some resources", and the conditions include the ResourceSpecification, quantity, and due date, then the plan generation code might notify the planner, either immediately or asynchronously, with some action selections, which might include:
* send such a request to Agent B this time, or maybe 
* make a rule to, in those conditions, always automatically send a request to Agent B with that information.

Agent B might have its own rule: when such a request arrives from Agent A, automatically generate a plan to fulfill it.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/136.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
