### ISSUE TITLE
Economic Events (valueflows)

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#16]
much like [activity streams](http://www.w3.org/TR/activitystreams-vocabulary/), it seems the fundamental data structure we want to support are events, in this case economic events.

questions:
- what are examples of events?
- what use cases do we want to support?
- do we care about non-economic events?
- how do events relate to [exchange](https://github.com/openvocab/exchange) and [process](https://github.com/openvocab/process)? are they the same or different?

when i think events i think [streams of data over time](https://github.com/substack/stream-handbook), [where each piece of data is an immutable message](https://github.com/ssbc/docs/blob/docs-rewrite/learn.md#learn-about-secure-scuttlebutt), which makes me think events are everywhere. but i'm wondering what others think. :cat:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/16.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
