### ISSUE TITLE
communicating Value Flows through visual design

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#17]
obligatory "logo thread", where we throw out random ideas for how to represent Value Flows as a scalable vector graphic (SVG).

personally, my visual impression of value flows are the images presented in [valnet/wiki/Value-Streams](https://github.com/valnet/valuenetwork/wiki/Value-Streams) and [valnet/wiki/Everything-is-connected](https://github.com/valnet/valuenetwork/wiki/Everything-is-connected), specifically:

![Sensorica value streams](https://camo.githubusercontent.com/aa0ca205c1f7280fc82f869899b0ea05e5bde4fb/68747470733a2f2f7261772e6769746875622e636f6d2f6268617567656e2f76616c75656e6574776f726b2f6d61737465722f76616c75656e6574776f726b2f736974655f6d656469612f6d656469612f70686f746f732f76616c75655f6e6574776f726b2e706e67)

and

[![Hypergraphic user interface](https://cloud.githubusercontent.com/assets/719605/10327163/b9f1c74c-6d00-11e5-943c-179e4025b1e9.png)](https://docs.google.com/drawings/d/14Ochj955jSTm2Upoa5VK6YfWkSlFGVWIEBdJ1WSJuxE/edit)

when i have time and feel a strong urge i'll try and draft some designs based on the above with a bit of Inkscape magic.

keen to hear what others have in mind.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/17.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.

**Comment by Erioldoesdesign** [comment]
Hi there, your riot chat link doesn't seem to be working and I cannot access the gitlab but I wanted to check if I can close this old job on the open source design job board: https://opensourcedesign.net/jobs/jobs/2015-10-08-valueflows

**Comment by fosterlynn** [comment]
@Erioldoesdesign apologies for lack of access in the gitlab, they had to close down open signup due to spammers. :(

Yes, please feel free to close that old job!  And thanks for asking.
