### ISSUE TITLE
interface design for accounts and transactions

### ISSUE THREAD

**Issue by simontegg** [valueflows/forum.valueflo.ws#20]
I'm starting a design research thread on visualising stockflows.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/20.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
