### ISSUE TITLE
network-to-network collaboration. presentation and demo to explain power of valueflows vocab and open app ecosystem

### ISSUE THREAD

**Issue by Connoropolous** [valueflows/forum.valueflo.ws#21]
Hey all!
We have this 2 day 'enspiral and friends' gathering happening on October 13-14 in SF, and I'm going to go down for it. Some of you may know of it, others may not. Here's some relevant comments about it
"Can we begin to imagine together, and create, a vision of the open, collaborative web that we could all build together, and find ways to collaborate between our organizations and initiatives?"
"Goals:
Building Relationships and Trust
Exploring what we might do together
Beginning to discover actionable next steps for community-to-community collaboration"

I think that what's going on here between us all is incredibly important to that conversation, and I'd like to be an advocate and interpreter for the vision that is being activated here, and the 'mad science' as Mikey says. 

I'd like to do that in multiple ways at the gathering, which I've already been preparing for. 
1. create a presentation with the intention of demystifying this openvocab conversation and sharing out that presentation ahead of time
2. hosting a conversation at the session where we open this topic for a while, and get feedback from the many non-technical people there, and how they interpret this, and try to develop clarity where it's lacking. this is with the hopes of rallying endorsement through understanding of those who are there
3. demoing a small prototype of the `personator`. A first, super primitive, web app that is equipped to play in the valueflows web application ecosystem. This can help ground the vision in showing that building things that actually work like this is within reach.
4. making mention of the 'linked-data-creator-api' and highlight how focusing on enablers developers to build valueflows based web apps by writing code libraries is a high leverage action, on the ecosystem level

You might have already seen this new repo that I created in the valueflows space... the `linked-data-creator-api`. Mikey has already said that he supports the development of this. I'd really love the input of @elf-pavlik on this though too, because frankly some of what I'm doing is actually really stretching my own knowledge. 
"enable github as database, json-ld style, using the valueflows `vf` vocabularies"
https://github.com/valueflows/linked-data-creator-api

And now I have a new little repo, which I think you all might like, its a (super simple) web ui where you fill out a form and it automatically creates a github repo with your jsonld file directly based off of the example `Person` json files that Mikey and Elf created. There's screenshots there, please check it out :) I actually think, @ahdinosaur, that this repo would be best suited to go in the `Holodex` org, which I'd also like to become a collaborator on, what do you think?
"A tiny web application whose sole purpose in life is to enable someone signed in with github to create, view, edit, or delete their personal linked open data profile with `type: Person`"
https://github.com/holodex/personator

One of the key concepts of the `linked-data-creator-api` library is that it keeps an index of all the open data created by the application(s) using it, for querying in a mongodb database. Basically a cache. THe various applications who wanted to create an ecosystem of open data would all connect to this same mongo database for the index of people/users, orgs, and all the other resources. Do others have a different understanding of how to federate the open data? Perhaps we could open a new issue, over in that repository if so. 

My main point in the presentation was going to be...
1. reduce the redundancy of all the 'personal profile' fields in the users table of the various web platforms such as loomio, cobudget, metamaps, hylo, NRP, etc. and all of the development hours that go into them
2. reduce the redundancy of the membership information for groups, in the various groups tables on platforms like hylo, cobudget, and loomio, and multiple developers managing code for group membership
3. enable the federation of a schema for resources used within platforms such as metamaps and hylo... projects, offers, intentions, requests, events, most of which show up in both platforms, but have no interoperability

This fits the goal of being modular because there is just one application that you would go to, to edit your profile. The apps themselves would begin to link to one another, for various functions, and different people within our network could focus on the maintenance of different aspects such as profile editing, and group membership administration. The apps would collectively rely on being signed in to/with github. 

Crazy ideas, but they actually feel kind of tangible at this point, relatively speaking :) I am seeking all of your input in the next few days as I begin a presentation. I'll post the link here as soon as I create it. I know this all might feel a bit of the blue, coming from me, but I've been doing my very best to keep up with these conversations, and looking for a while for the high value "way in". 

I think that it will be powerful to bring something to the gathering that has elements of co-creation between those of who have worked within these various spheres and networks such as Edgeryders, OuiShare, Metamaps, Enspiral, Sensorica, and such :)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/21.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
