### ISSUE TITLE
Discovery of (Qualified/N-ary) Relations

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#22]
Given as starting point URI denoting an agent or even any resource, how do we find information about various relations which involve this agent (or resource)? We shouldn't assume that making HTTP GET request to this URI will include in response *_all_ those realtions(ips), especially if we just want to get the name and avatar ...

**TODO** add few possible solutions to that problem

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/22.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
