### ISSUE TITLE
Digital Signatures

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#23]
Capturing very early just to let it brew slowly in our minds. Since we deal with agreements, trust relations etc. We need to make sure people can rely on technology they use. Some relevant work in this field which I follow.
- http://opencreds.org/ (see videos on the bottom of the page)
- https://github.com/digitalbazaar/jsonld-signatures
- http://manu.sporny.org/2013/sm-vs-jose/

More long term tools which can help people feel comfortable about their private keys, especially ones used for 'high stake' agreements/contracts.
- http://www.w3.org/TR/WebCryptoAPI/
- https://www.nitrokey.com/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/23.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
