### ISSUE TITLE
Relation(ship)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#24]
Since all components of this vocab will work with relationships, I see benefit with defining their generic form on this level and crating more specific ones in separate repositories as needed.

Use cases:
- https://github.com/valueflows/agent/blob/master/use-cases/resource-agent-relationships.md

See also:
- #52 - owl:inverseOf
- #59 - Discovery of (N-ary|Qualifed) Relations

Elsewhere:
- http://www.w3.org/TR/activitystreams-vocabulary/#dfn-relationship

**WORK IN PROGRESS**

(currently reusing diagrams from [here](https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property))

Direct relation

![direct relation](https://docs.google.com/drawings/d/1xcuJoZDrVmd3zGTIaxlMf1FQVoU0fKxpnzsvTHd3Ojo/pub?w=960&h=720)

Qualified relation (using same property in both directions)

![relationship](https://docs.google.com/drawings/d/1UT8vXtcsZ20KzrrxZor8NP_FfbQKzuHDaz8AYvv9Rr0/pub?w=960&h=720)

**inverse/reverse**

![relationship reverse](https://docs.google.com/drawings/d/1DywlWRat6GN7PjC03H__7Y4SgbObNIs38IWFyS8mZNs/pub?w=960&h=720)

based on [Reification](http://www.w3.org/TR/rdf-schema/#ch_reificationvocab)

![reification](https://docs.google.com/drawings/d/1FrjE9XW8QUJOrcVHK6_eTsysPFNdBtRsTnjCKbBEEyI/pub?w=960&h=720)
### Proposals
- vf:property instead of vf:relationship (from https://github.com/valueflows/agent/issues/46 )
- vf:QualifiedRelation instead of vf:Relationship http://patterns.dataincubator.org/book/qualified-relation.html
- vf:NaryRelation http://patterns.dataincubator.org/book/nary-relation.html | http://www.w3.org/TR/swbp-n-aryRelations/

![QualifiedRelation](https://cacoo.com/diagrams/17WIaaFrC34qV87v-E4CE5.png?t=1444741538589)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/24.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
