### ISSUE TITLE
Spatiotemporal mapping

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#27]
value flows through space, here's a thread for dedicated conversion regarding this. feel free to share ramblings, share prior work, discuss ideas, propose actionable steps, or anywhere in between.

some opening questions from @iainkirkpatrick:
- how do we define space? e.g. physical, online, emotional spaces
- how do we visualize space to tell the story of the data?

some previous comments relating to this topic:
- https://github.com/valueflows/exchange/issues/8
- https://github.com/valueflows/valueflows/issues/21#issuecomment-133908515

/cc @almereyda

**Comment by almereyda** [comment]
Thanks @elf-pavlik for your maintenance.

Please find the latest discussions about GeoJSON-LD in

- https://github.com/w3c/json-ld-syntax/issues/4
- https://github.com/w3c/json-ld-syntax/issues/7#issuecomment-421077425
- https://github.com/w3c/json-ld-syntax/issues/33#issuecomment-412942505

plus

- https://github.com/w3c/json-ld-syntax/pull/41
- https://github.com/w3c/json-ld-api/pull/16

and also

- https://github.com/LinkedPasts/linked-places/
- http://kgeographer.com/category/geojson-t/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/27.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
