### ISSUE TITLE
Valuing as qualifications of Agent -> Resource relationship

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#28]
Following https://github.com/valueflows/valueflows/issues/69#issuecomment-148892583

I would propose that we stay very careful wherever we introduce anything related to some agent **valuing** some resource. If we take direct relationship

Agent - wants -> Resrouce

(eg. elf Pavlik wants a piece of cake)

We can reify it and than qualify it with anything related to valuing 

Agent <- subject - Want - object -> Resource

(eg. Want of elf Pavlik for a cake, as long as this cake got made with vegan and fair trade ingredients)

So **valuing** related qualifications would refer to a Want (or an Offer) not to the Agent or to the Resource!

See also:
- #63 
- #62

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/28.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
