### ISSUE TITLE
ESSglobal

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#3]
- http://www.essglobal.info/
- http://purl.org/essglobal/vocab/v1.0/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
