### ISSUE TITLE
Social Impact of ValueFlows

### ISSUE THREAD

**Issue by simontegg** [valueflows/forum.valueflo.ws#31]
What impacts do you think valueflows will have, or would you like it to have? Why is it important to you?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/31.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
