### ISSUE TITLE
Valueflows' "value proposition" to developers

### ISSUE THREAD

**Issue by simontegg** [valueflows/forum.valueflo.ws#32]
What does valueflows offer developers? 

This has been on my mind because Enspiral is planning to opensource and put some energy into "My.enspiral" - the software we use to create virtual accounts and transact money within a company while reducing overheads. 

A year ago @bhaugen wrote a pretty good description of one of the main use cases [here](https://github.com/valueflows/valueflows/blob/master/use-cases/enspiral.md) and its overlap with valueflows. The other week I started a  [design exploration thread](https://github.com/valueflows/valueflows/issues/53) targeted at my.enspiral. I've put my hand up to help with the design and development but I imagine work won't really get going until the new year. Since enspiral is a do-acracy and I will be doing some of the doing I hope to influence  my.enspiral to align with valueflows but I don't have good understanding what that means. 

I'm not sure yet but lets say that redevelopment means spitting the app in to an API and a frontend. It would be great if the API could handle syncing accounts and company level transactions with [Xero](https://www.xero.com/) and also with a third app for a specific collaborative funding use-case [Cobudget](http://cobudget.co/). 

Imagine you're a sceptical developer of my.enspiral.  In the projects you've worked on you've seen the benefits of keeping a tight scope and minimising coordination costs by giving the lead dev autonomy over implementation details.

Why would you give up your hard earned autonomy over technical implementation to do things the "valueflows way"? How will this benefit the redevelopment, and ultimately users? What does "valueflows way" even mean in practice? Won't that blow out the scope of the project? Isn't software development about meeting and responding to user needs (agile), rather than conforming to abstract prefigured requirements (waterfall)? :)

Thinking about this case may help us get develop better comms in general

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/32.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
