### ISSUE TITLE
Physical vs. Virtual (Online, Legal, Conceptual)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#34]
I would like to start drawing clearer distinction about which terms refer to _physical_ entities, activities, relationships and which to _virtual_. I find it useful to pay attention when we work within frame of physical reality with various 'laws of physics', when do we work with online dimension with various 'protocols', when do we work with formal legal frameworks with various rules and when do we work with conceptual framework with various ideas and fantasies. Some examples:
- Person - physical, legal (via legal identities), online (via online accounts)
- Group - conceptual, all physical interactions happen through individuals who co-create it, for me one of the major reasons to have common property which connects them
- Bot - online, managed by a person or many people
- Organization - legal, online (via online accounts managed by people and possibly bots)
- MoneyTransfer - virtual, legal (possibly online depending on monetary currency used)
- OwnershipTransfer - conceptual (possibly legal)
- Transport - physical
- ownedBy - conceptual (also legal)
- carriedBy - physical
- locatedAt - physical
- controledBy - possibly worth distinguishing between operating some machine in physical way or influencing something in conceptual way 

I will try to experiment with it in examples I work on as well as writing down notes on markdown page of each term.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/34.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
