### ISSUE TITLE
WWHEE

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#35]
What I want to emerge from this project: World Wide Holonic Economic Ecosystem.

Like the World Wide Web for economic interactions. Should be usable from any browser or app or email or text message or command line. Plug in and participate in conversations for action, processes, transfers of resources, etc etc etc.

Does this make sense to anybody else?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/35.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
