### ISSUE TITLE
Seperating conversation spaces

### ISSUE THREAD

**Issue by almereyda** [valueflows/forum.valueflo.ws#36]
As this repo holds the main conversation around value flows, but mixes organisational and vocab related discussions, I am proposing to [seperate conversation spaces](https://discourse.transformap.co/t/principles-we-can-agree-upon/249/5?u=almereyda) and am willing to offer free (as in drugs on the table) and maintained Discourse hosting to `valueflo.ws`.
Having read a few days ago how a better DVCS would also store issue conversations alongside, it struck me how much knowledge we give up to GitHub instead of, again, retaining data ownership of it.

Instead, as we are having good experiences with GitLab (or Gogs?), one could even think to federate this conversation + endeavour's infrastructure even further. Knowing how dangerous it can be in terms of spontaneous cooperation with strangers.

**Comment by fosterlynn** [comment]
@almereyda thanks for thinking about these issues!  Really! It would be good to get out of github at some point, obviously.  And I understand the chat bridging issues are a pain.  

But I have to admit to feeling a lot of inertia myself.  There is so much going on, I don't know if we collectively have head space or time to migrate our infrastructure.  And there is this history of a lot of people in and out of VF discussions, I don't want to cut people off if they are not paying attention for a while.  And gitlab will have its own issues in the future, given their business plans.  (Are these real or are these excuses??)

**Comment by elf-pavlik** [comment]
see last event :point_up: transfering all open ended discussions to `valueflows/forum.valueflo.ws` repo to sort out all the actionable issues we should tackle as part of next milestones in `valueflows/valueflows`

**Comment by almereyda** [comment]
If the person managing the `valueflo.ws` DNS zone would create these records for the `forum` subdomain

Record | Content
--- | ---
A | `5.9.123.36`
MX | `email.ecobytes.net.`
SPF/TXT | `v=spf1 a mx ~all`

it seems migrating the contents from here would be very easy and even officially supported.

* [Introducing GitHub Issues to Discourse - plugin / extras - Discourse Meta](https://meta.discourse.org/t/introducing-github-issues-to-discourse/46671)
* [GitHub Issues to Discourse Mover](https://www.discourse.org/github)
* [discourse/github-issues-to-discourse](https://github.com/discourse/github-issues-to-discourse)

If Ecobytes seems too far away for good use in the Americas, there is even a chance to get a fully managed instance donated by the original developers:

* [Free Discourse forum hosting for community-friendly GitHub projects](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/)

---

Please also note `#valueflows:matrix.org` now exists.

- https://matrix.to/#/#valueflows:matrix.org
- e.g. via https://riot.allmende.io/#/room/#valueflows:matrix.org

**Comment by elf-pavlik** [comment]
Thanks @almereyda we should consider that once more people joins the discussion.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/36.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
