### ISSUE TITLE
How will systems using the ValueFlows vocab and protocols work?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#37]
I have some ideas, which I will sketch out later, but am even more interested in your ideas.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/37.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
