### ISSUE TITLE
Can query a list of resources

### ISSUE THREAD

**Issue by pmackay** [valueflows/forum.valueflo.ws#38]
As a citizen I can query a list of resources in my local area, so I can find out what useful resources could help with my needs.
- These would be categorized against a list of ResourceTypes.
- They would have relevant location information where applicable.

---

Is there an intent to add more fields to https://github.com/valueflows/resource/blob/master/context.jsonld? Would it compare closely with http://schema.org/Thing?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/38.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
