### ISSUE TITLE
GoodRelations

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#4]
- http://goodrelations-vocabulary.org
- http://purl.org/goodrelations/v1
- maintainer: https://github.com/mfhepp

also: http://www.productontology.org/ (wraps dbpedia/wikipedia)

Please edit this comment directly to keep it as summary of all the conversations bellow
### Agent, Offer|Demand, Product|Service (+properties)

Nice overview in this comment: https://github.com/schemaorg/schemaorg/pull/821#issuecomment-146123021
#### Product or Service
- https://github.com/schemaorg/schemaorg/issues/134
- https://github.com/schemaorg/schemaorg/issues/801
#### Commercial Bias
- https://github.com/schemaorg/schemaorg/issues/424
- https://github.com/schemaorg/schemaorg/issues/764

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
