### ISSUE TITLE
Commons vs private property

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#40]
My view of valueflows (with which you may disagree) is that we are defining a vocabulary and protocols for an economic transition, from capitalism to something else that is trying to form itself through many experiments. Which means the vocab needs to work now, and also work in alternative forms, often intertwingled.

One of the probable institutions of the next economy is The Commons, which was famously studied by [Elinor Ostrom](https://en.wikipedia.org/wiki/Elinor_Ostrom).

Christopher Allen recently revised [Ostrom's Design Principles for Collective Governance of the Commons](http://www.lifewithalacrity.com/2015/11/a-revised-ostroms-design-principles-for-collective-governance-of-the-commons-.html).

A lot of the discussions we've had recently in Gitter and elsewhere have been to isolate transfers of ownership, assuming somebody owns the resource and is transferring ownership to somebody else, from other resource flows - especially those that do not assume transfer of ownership, or maybe do not assume private ownership at all. How would transfers of resources behave in The Commons? It's not free-form, where anything goes. You are accountable to The Commons.

I'll excerpt Allen's whole list, but do click through to read why he says he revised Ostrom's original principles.

> How to Avoid the Tragedy of the Commons within Self-Organizing Systems
> 
> 1A. DEFINE AUTHORIZED USE: The community of those who have the right to use the common resource is clearly defined.
> 
> 1B. DEFINE COMMONS BOUNDARIES: The boundaries of the commons are clearly defined so as to separate the usage rules from the larger environment.
> 
> 2A. MAKE COSTS PROPORTIONAL: Costs for using and maintaining the commons are proportional to the benefits that those users receive from the commons.
> 
> 2B. PAY ALL COSTS: People that use the commons keep costs inside the local system as much as possible. They do not externalize costs either to neighbors or future generations.
> 
> 3A. DECIDE INCLUSIVELY: Everyone who benefits from or is affected by the use of the commons makes choices about it. This includes decision-making on resource allocation and on rules and responsibilities for use of the commons. Members of the community operate with respect and mutual regard for each other.
> 
> 3B. ADAPT LOCALLY: Members of the community adapt the rules and culture for the commons to local needs, resource qualities and environmental conditions.
> 
> 4B. SHARE KNOWLEDGE: All members are actively engaged in observing and sharing knowledge about the conditions of the system.
> 
> 4C. MONITOR EFFECTIVELY: Monitors who are members of (or supported by and accountable to) the community view and report on the use and maintenance of the commons by community members and others.
> 
> 5 . HOLD ACCOUNTABLE: Violators of the rules or culture of the commons face graduated sanctions, proportional to the seriousness of the transgression. These are applied by members of the community or by others who are accountable to community for applying such consequences.
> 
> 6 . PROMPTLY RESOLVE CONFLICTS: The community offers inexpensive, fast and easy access to mediation for effective conflict resolution.
> 
> 7 . GOVERN LOCALLY: Community self-determination is recognized and supported by higher-level authorities.
> 
> 8 . CONNECT TO RELATED SYSTEMS: Any side effects or other repercussions by one community to another in managing their commons, should be addressed in the context of larger, nested communities that have a legitimate role in those consequences. These externalities should be resolved by the community at the most immediate or local level (aka subsidiarity) that can operate from effective human relationships, rather than by a faceless authority.
> 
> ALT 8. COORDINATE WITH RELATED SYSTEMS: For groups that are part of larger social systems, there must be appropriate coordination among relevant groups. Every sphere of activity has an optimal scale. Large scale governance requires finding the optimal scale for each sphere of activity and appropriately coordinating the activities, a concept called polycentric governance. A related concept is subsidiarity, which assigns governance tasks by default to the lowest jurisdiction, unless this is explicitly determined to be ineffective.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/40.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
