### ISSUE TITLE
We must be doing something wrong...

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#41]
@edwardwest in Hylo said,

> I want to make sure that @Mikey Williams in particular gets a sense for CEPTR and it's aims, as it may simplify some of what Value Flows is proposing.

https://www.hylo.com/p/11921

Which implies to me that we must be proposing some unnecessary complexity.

@ahdinosaur ? @edwardwest did you get the ping? Can you explain what unnecessary complexity we are imposing? Doesn't seem like a good thing...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/41.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
