### ISSUE TITLE
Conway's Law

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#42]
> organizations which design systems ... are constrained to produce designs which are copies of the communication structures of these organizations
> 
> — Mel Conway

This law also works in reverse. Your system architecture will constrain the organization that can develop around it. If we want  decentralized, diverse networks of people, so must be the system architecture.

When @fosterlynn and I set out to develop the NRP software, we knew it was the wrong architecture (a monolith), but we did not have many practical choices because of our own constraints of people, skills, money and time.

But (we think) because it was a monolith, and huge, and complex, nobody else has wanted to work on it.

We jumped into the Open Apps Ecosystem and the Value Flows as the antidote.

I write this down as an issue, because I'm seeing a lot of newer initiatives that claim to be decentralized, but in fact have hard dependencies on something that either is itself centralized (e.g. blockchains, where you have a hard dependency on one blockchain, however many copies may be out in the wild) and/or monocrops (Ethereum) where everybody needs to use one technology in order to interoperate.

Linked Open Data does not seem like that to me.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/42.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
