### ISSUE TITLE
Intent - Commitment - Reality

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#44]
Ref. issue #96 but starting a new issue for the discussion evolving into Intents.

I haven't thought a lot about Intents, as others have more experience there.  But to get my head into it, I made a tentative UML diagram.  (Sorry all you LOD people, I'll get there!)

![intent-commit-reality](https://cloud.githubusercontent.com/assets/3776081/11752434/2d2d4646-a005-11e5-9fb1-b8190b3371db.png)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/44.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
