### ISSUE TITLE
signal: intent -> plan -> reality

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#48]
from https://github.com/valueflows/valueflows/issues/62#issuecomment-152401068, i propose we formalize the concept of a signal within a conversation for action as a `Signal`, then rename and split out the sub-types of signals:
- **Intent**: [express wish for transaction](https://github.com/valueflows/intent)
- **Plan**: express commitment to do transaction
- **Reality**: express that transaction is done
- ... possibly more?

with this, i recommend we either
1. combine all the signal concepts into a single `signal` repo
2. create a `signal` repo to be an overview and index for all the types of signals

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/48.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
