### ISSUE TITLE
Uncertainty and probability issues

### ISSUE THREAD

**Issue by gcassel** [valueflows/forum.valueflo.ws#49]
Uncertainty is a fundamental aspect of natural sciences, and an important although IMO underdeveloped part of game theory.   (Not underdeveloped so much because of lack of awareness or interest, but because it's damn tricky stuff.)

I bumped into this new blog:  https://medium.com/guesstimate-blog/introducing-guesstimate-a-spreadsheet-for-things-that-aren-t-certain-2fa54aa9340#.xloa48kaf
I'm not aware of anything quite like it: an open source project for probability-based spreadsheeting.   I reckon that such tools can quite easily be misused, but can also be fundamentally useful.  

I think that expressions of uncertainty should ideally be be available for recipes and plans in Processes, especially for physical processes and models of natural systems.   Like I said earlier, probability in game theory is damn tricky, and this inevitably influences systems (designed OR naturally emergent) which are at least partly described by _input-types_ by Agents in one or more defined _roles_.    I reckon this practically limits the applicability of probability not only to multi-Agent Processes, but also to Economic Actions. 

A few questions: 
1. Does anyone think there are any rational places in the existing Value Flows taxonomies to apply the concept of uncertainty? 
2. Does anyone foresee that uncertainty will fit in to taxonomies which haven't developed here yet?
3.  Is anyone aware of anything else like that Guesstimate project?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/49.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
