### ISSUE TITLE
SKOS

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#5]
- http://www.w3.org/2004/02/skos/
- http://www.w3.org/2009/08/skos-reference/skos.html
### Examples
- http://aims.fao.org/skosmos/agrovoc/en/index | [mailing list](https://groups.google.com/d/forum/agrovoc)
  - http://aims.fao.org/aos/agrovoc/c_8893.html (apple juice)
  - http://aims.fao.org/aos/agrovoc/c_16148 (soups)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/5.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
