### ISSUE TITLE
introducing Matt and Clive

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/forum.valueflo.ws#51]
@mmckegg, a friend and open source collaborator of mine, and @cmckegg are keen to collaborate with us on Value Flows, yay welcome. :cat: :tada: :two_hearts: 

to get the party started: Matt and Clive, would you mind sharing your story that brings you here and what you wish was possible in your local networks?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/51.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
