### ISSUE TITLE
Does a VF message broker make sense?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#52]
Might be a bot, vaguely resembling [Huginn](https://github.com/cantino/huginn) (but don't take that literally).

Would have two sides: one for senders of messages, and one for receivers.

In the middle would be the VF vocabulary, with a mapping table from the sender's content on that side, and a map for the receiver's content on the other side. The broker would translate the sender's data into the VF vocabulary and then translate from VF to the receiver's format.

A sender could map their message format once, and a receiver could map their message format once, and the broker would be able to translate from many senders to many receivers.

I'm not thinking a single broker, but something easily deployable so many of them could be set up, but a single sender or receiver might want to have an address for their broker.

The brokers could also send messages to each other using pure VF vocab, no translation required. So if a sender and receiver did not use the same broker (which I assume would mostly be true), their brokers could connect to each other.

Does this make any sense? If so, what are some easy ways to implement and try it out? And how about some use cases?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/52.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
