### ISSUE TITLE
Revisiting the dreaded "Task"  

### ISSUE THREAD

**Issue by gcassel** [valueflows/forum.valueflo.ws#53]
I've been driving (myself batty) around the intersection of economic networks with social processes for discussion, deliberation and decision.  In doing so, I keep feeling that there's a significant role for 'tasks' within communities, projects and organizations.

'Task' doesn't really fit into any existing VF vocabulary.  In theory, it could be related to the future Commitment vocabulary.  That could be an indirect relationship, whereby a group's evolving 'tasks' must be _translated_ into specific Commitments.  Tasks could also be indirectly related to the Process vocabulary, because my current definition of task can directly indicate _designed functions_ within designed systems.  _However_, I'm not trying to make conversation about the Process vocabulary, which has IMO progressed effectively.

So, all I'm really doing here is making a **request for comments** on my latest conception of 'Task' in [General Principles of Agreement-Based Organization](https://docs.google.com/document/d/1w53bAMDErx7FWzJJVxFR0ggaWubc6wbs-etQdUgn1-8/edit?usp=sharing) , which is not directly related to VF.   

Any thoughts on the passage below?  

---

"Tasks indicate _decisions for action_.  Tasks describe processes which a person or group _intends_ for identified agents, or _types_ of agent, to perform.
- Importantly, an individual can (and often does) assign tasks to oneself.  However, we’re mainly concerned here with social understandings and agreements.
- Many action-oriented projects and agreements could ultimately be defined as tasks. I.e., they are identified with a directly responsible person or group, and are expected to _end_ with the creation of one or more defined outputs.
- Tasks may be performed by human agents _or_ non-human agents, such as machines.
- Tasks may include the administration and regulation of predictably recurrent processes.  Such tasks are _systemic functions_.
- Specific tasks within a system or group may be openly available to interested parties, or assigned via _roles_."

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/53.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
