### ISSUE TITLE
Goal (Intent?) -> Recipes -> Plans -> Reality (eg. our online meetings)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#54]
Just capturing one of possible ways to look at economic interactions, with emphasis on diversity among available recipes, flexibility in plans, together providing us with multiple way of reaching the same goal.
### Goal (Intent?)

The purpose of certain activity, what do we want to accomplish?
**Sync-up our individual progress on VF and plan next steps**
### Recipes

We can achieve intended goal in many different ways / multiple recipes can serve the same purpose
1. Asynchronous conversation on online forum
2. Synchronous conversation via online chat
3. Synchronous conversation via online voice/video call
4. Synchronous conversation face2face (IRL)
### Plans

Each of recipes can have multiple plans where we use different variants of compatible ingredients. Let's pick recipe nr 3 - Synchronous conversation via online voice/video call

Input options for _Online Conference Room_:
- Google+ Hangout
- Jitsi
- Talky

Input options for _Scribing Pad_:
- Etherpad
- IRC channel
- Gitter channel

Let's pick: _Jitsi_ & _Etherpad_ and _Talky_ & _Gitter channel_ as fallback options 

We also plan to meet 5 people: Lynn, Bob, Mikey, Greg, Pavlik
### Reality
1. _Etherpad_ didn't work so we used _Gitter channel_
2. 5 people participated but Bob couldn't join and Paul did show up

Since we mostly do online collaboration all together and through that co-create something that we hope people will value, I would propose to give some attention to exercise modelling our common economic activities.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/54.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
