### ISSUE TITLE
Refining Questions - Interviews - #DistroResearch

### ISSUE THREAD

**Issue by coopchange** [valueflows/forum.valueflo.ws#55]
@fosterlynn recommended I make an issue space for an interview series I'm doing to refine my independent research project's questions.
My starting place was:
♦ Why & How do people share assets (i.e. information & resources) online?
♦ What are the cultural & place-based obstacles (e.g. identity, norms, abilities) that prevent people from realizing the potential of digital asset-sharing?

and you can see a more full (but still short) background [here](http://tiny.cc/distroResearch)

you can announce your interest on this issue or by starting the process, filling out this 90 second pre-interview [form](https://docs.google.com/forms/d/16gvXwNFQ-pDpF5cQrNHgmXrpjZXsFzW9zEeNSgWNflA/viewform)

I'm hoping to do most of these through video call (zoom.us), but by writing is fine too! They can be recorded or not, with the distribution & CC licensing determined by the interviewee.

If folks like, I will post the interviews (as made available by their participants) here, and write a wrap-up of sorts to let you know what direction my research will be launched by the feedback.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/55.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
