### ISSUE TITLE
Minimalism or not

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#56]
One of the principles of the REA ontology, whether stated explicitly or not, was minimalism. The minimal number of concepts that could cover the domain, originally of accounting, and eventually, economic networks.

If something could be delegated to another ontology, it was. 

So how much, how many concepts, how many complications, do we want to include in the VF vocabularies? This is not a hard and fast line. As in all design spaces, one or more sweet spots can be found.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/56.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
