### ISSUE TITLE
Bill McCarthy's latest slides

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#57]
[The whole deck](https://drive.google.com/file/d/0BxlqOeaPnXHfRmE3RFFNdVJfRWs/view?usp=sharing) for possible discussion. @dan-mi-sun did the financial claims section make sense to you?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/57.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
