### ISSUE TITLE
A VF "terminology directory"

### ISSUE THREAD

**Issue by gcassel** [valueflows/forum.valueflo.ws#59]
I think this idea has come up, but I haven't seen an existing Issue for the subject of a VF dictionary/glossary/encyclopedia/whatever.

I'm picturing the potential value of a central "terminology directory".  The directory could include direct descriptions of some terms, but link to official documents for other terms.  (Some terms seem to already have literally _definitive_ md documents, distributed across several repositories.)

The directory itself would be a new doc, and could be linked in VF's main [README](https://github.com/valueflows/valueflows/blob/master/README.md)  and/or the (maybe irrelevant?) wiki.  

Any thoughts?  

I haven't authored a Github doc before, but if people like the idea of a terminology directory, this could be a good place for me to start!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/59.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
