### ISSUE TITLE
value equations and barter

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#60]
I don't understand to much of current approach to value equations. I have impression that it assumes that all agents participating in it cast a intent to receive (_[vf:Request](https://github.com/valueflows/intent/blob/master/Request.md)_) a particular type of monetary currency - common for all those agents.

I would find it interesting to see how such equations can work with barter and multi-party barter https://github.com/valueflows/exchange/issues/19 . For example:
- many of the contributors cast an intent to receive (_vf:Request_) _peanuts_
- few of the contributors don not cast such intent
- on of the the contributors has allergy to them so casts explicit intent NOT to receive _peanuts_

In that scenario, someone offers to barter (vf:Exchange) **a part** of what all those contributors co-created for certain amount of _peanuts_. Since many. let's even say most, of the contributors cast intent to receive _peanuts_, in many cases such offer should get accepted and they should have a way to distribute peanuts among themselves.

In such scenarios, next offer of barter may include something what other contributes cast intent to receive. Then they will have possibility to receive what they want.

Depends on the quality of relationships (trust, care etc.) between those contributors, some cases might require some kind of internal mutual credit to help with equations...

Myself I plan to participate in goods (not income) distribution, but ASAP I want again stop casting intent to receive monetary currencies. Some of my diverse intents to receive Products and Services may link to many matching intents to provide (_[vf:Offer](https://github.com/valueflows/intent/blob/master/Offer.md))_ cast by other agents. In near future, very likely many agents casting those intents to provide, will also cast intents to receive monetary currency. In that case long chains of multi-party barter could work. Where some peers would do clearings in-kind and other peers would exchange various kinds of monetary currencies, where various types of ISO4217, mutual credit, blokchain coins, time hours etc. could participate in those chains.

see also: 
- [agent can benefit from keeping intended Transactions not coupled into intended Exchanges](https://github.com/valueflows/intent/issues/5)
- [Make 3D printed part](https://github.com/valueflows/valueflows/blob/master/use-cases/make-3d-printed-part.md)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/60.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
