### ISSUE TITLE
connect with peerconomy

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#61]
Once we merge #115 I would like to invite @ChristianSi to collaboration. Please check out book he wrote available at http://peerconomy.org/wiki/Main_Page His ideas have evolved since then but I still find it very inspiring read.

In #120 I mentioned http://liquidfeedback.org it looks that now Christian works on https://liqd.net/en/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/61.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
