### ISSUE TITLE
Action verbs model [was Event Types...]

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#63]
I have been lately representing event types as subclasses of event.  Like [here](https://github.com/valueflows/process/issues/5#issue-115766465) and [here](https://github.com/valueflows/exchange/issues/12#issuecomment-157875673).  (Also been trying out calling an Economic Event a Value Flow, so consider those equivalent names for this discussion, and we'll work on the naming separately.)

As I knew at one point but forgot, and was reminded by @bhaugen , that works fine if you are only talking about the "actually happened" layer.  But then you need the same concept at both "recipe" and "plan" layers.  Event types define within the recipe what types of events will occur; and commitments on the plan layer also refer to an event type.  So now if you use subclasses, you have 3 parallel layers that basically define the subclass same structure for different things.  Ouch.

In our software, we have a class called EventType that stores all the event types and all events, commitments, and recipe parts know their event type.

There are a limited number of them, and they are well defined. 

Is there any other alternative?  Could we define the subclass structure on the recipe layer and just refer to those classes to define the behavior?

Opinions?  Especially how would one naturally think about it is LOD / RDF land?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/63.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
