### ISSUE TITLE
What do "internal" and "external" mean in value flows?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#66]
See https://github.com/valueflows/process/issues/18#issue-157317535

@elf-pavlik wrote:

> It looks like we can distinguish 6 sources for allocating resources as inputs for the process:
> 'internal'
> [...]
> 'external'
> [...]
> The 'internal' and 'external' seem to differ only that it may require a vf:Transfer, while internal we can do allocation without any transfers. 

I replied:

> 'Internal' and 'external' are interesting concepts that deserve their own thread. Internal to what? (That's why we have contexts, or context agents.) What does 'someone else's inventory' mean? What does it mean in a mutual coordination economy?

This is that thread (to discuss internal and external to what).

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/66.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
