### ISSUE TITLE
Proposal for a VF project for the Mutual Aid Network Mapping Summit

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#68]
@fosterlynn and I just spent a week in Madison WI at the Mutual Aid Network Mapping Summit.
- [overview](https://docs.google.com/document/d/1n1yOZ8UkaXYETFcosBShxGgWzuGdqx-h9u4bEmpdqPA/edit?usp=sharing)
- [videos](https://www.youtube.com/channel/UCBmSlCSPu-cs3GCAkzIe6dA)

At their invitation, we introduced our older regional economic analysis software, also based on the REA ontology, [Locecon](http://locecon.org/). This was part of the [programme I outlined in 2005](http://mikorizal.org/BeyondTheEnterprise.html) for what I planned to work on as I retired.

Locecon takes the VF model and vocabulary to an aggregate level, where Economic Functions represent groups of Economic Agents doing roughly the same kinds of production.

The Mutual Aid Network participants picked up on the idea and even started calling it "value flows". Here's [the value flows model we all co-created during the summit](http://locecon.org/clusters/cluster/25/).

People in Chicago and Asheville North Carolina are also starting to try the software.

The problem is that the software is something that I hacked together for [this project in Nova Scotia](http://locecon.org/nova-story/). It needs a lot of work (I called it "user-hostile"), and is the wrong architecture for the problem.

All of these communities, and all of the agents in these communities, want to be able to create their own economic profiles somewhat independently but have them be findable, shareable, linkable, and combinable in geographic maps as well as resource flow diagrams.

They also want to be able to summarize actual detail economic data to populate the numbers in the aggregate regional-analysis models. Here's [a sketch we wrote for a conversation with the TransforMap people](https://docs.google.com/document/d/1CWaMM76bM4re_TabCyHQOLkqYbP8QxO2ZP3fn4CJOF4/edit?usp=sharing) comparing their model with an OVN model (like Value Flows) and the Locecon model. 

We described this idea in a hand-wavy sort of way at the summit and got enthusiastic and universal approval.

A VF vocab and linked open data could be the perfect architecture.

What do you all think?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/68.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
