### ISSUE TITLE
roles in supply chain

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#69]
I think we may want to analyse different roles in supply chains. For example
- producer
- distributor

_NOTE: we would NOT define them as disjoint, so agents acting as producer can at the same time act as distributor_

I think it will relate to how product models (~ resource types) get used in offers/requests. Producers would create identifiers for their product models e.g `itacatealimentos:olive-oil-0.75L-in-wine-bottle` which distributors would use in their offers for products of that type e.g. `bbfoodcoop:offers/members/itacatealimentos-0.75L`

Producers should take responsibility for relating their product models to generic resource types e.g
- _prodont:Olive_oil_
  - _itacatealimentos:olive-oil-0.75L-in-wine-bottle_

But distributors in their datasets, could always augment product model descriptions with statements about their relationship to generic (commonly referenced) resource types. In many cases they could even try to make PR and get those statements added 'upstream' (in producers dataset)

Related to: https://github.com/valueflows/resource/issues/26

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/69.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
