### ISSUE TITLE
Data Food Consortium: Building a common language

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#7]
See https://github.com/ouisharelabs/food-dashboard/issues/1#issuecomment-310080676 and the rest of that thread from there, expecially https://github.com/ouisharelabs/food-dashboard/issues/1#issuecomment-310097884 

Also http://datafoodconsortium.org/blog/building-a-common-language-our-semantic-business-concepts-model

How should we approach this?

**Comment by babonet13** [comment]
@bhaugen : Difficult to answer, because people putting so many different things behind the word "requirement" ! 
1 is the "why doing something ... for which purpose ..."

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
