### ISSUE TITLE
Secure Scuttlebutt

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#70]
@ahdinosaur wrote in https://github.com/valueflows/valueflows/issues/60#issuecomment-226991141

> by default, you are replicating the feeds of those you follow and those who they follow (friend-of-a-friend / two degrees of separation), so as with most common social networks as long as you're friends with a super-node, you're good. there's talk of being able to ask specific friends for a specific message, in order to fetch missing messages within a thread, but it's still not a global fetch.

When someone sends me a link to a message published by someone I do not follow. To get that linked message, person who sent me a link needs to replicate the whole feed of an agent who published that linked message?

When I want to send link to that message to yet someone else, do I also need to start replicating myself the whole feed in which that message got published?

Above makes sense to me in twitter like scenarios where we mostly interact with people who follow us, but I don't know if this applies well to something like ride sharing where we mostly interact with people we don't know at all.

Even in twitter like scenario, in SSB network, how do you `@mention` someone who doesn't follow you? How do you provide functionality similar to https://www.w3.org/TR/webmention/ ?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/70.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
