### ISSUE TITLE
Solid

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/forum.valueflo.ws#71]
@bhaugen wrote in https://github.com/valueflows/valueflows/issues/139#issuecomment-228151321

> @elf-pavlik it might be interesting to have a parallel conversation about how to implement OFN using Solid...?

I agree with that, two links to features of Solid which I currently don't see in SSB
- https://github.com/solid/solid/blob/master/proposals/notifications.md
- https://github.com/solid/web-access-control-spec

I'll work on examples how people included in ACL can post offers on behalf of some food provider. As well as how 'random strangers' can respond to those offers. (~ place an order)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/71.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
