### ISSUE TITLE
Compare REA to traditional financial accounting

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#72]
Spun off from https://github.com/valueflows/valueflows/issues/30

This issue is to explore all of the angles of  this subject, starting the economic events vs journal entries.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/72.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
