### ISSUE TITLE
Time bank use cases

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#74]
Starting an issue so we can explore the use cases that time banks provide.  

Ping @stevebosserman - let's figure out how best to do this.

**Comment by matslats** [comment]
Yes I get that, but I have a use-case here probably much more serious
than a favours system between fans of a niche technology.
If I want to build a table showing the running balances of 20 users from
a log of 10,0000, which, with the data structure proposed means 20
queries of the form
> SELECT SUM(amount) FROM table WHERE *payer* = $user_id  - SELECT
> SUM(amount) FROM table WHERE *payee* = $user_id
is performance a concern?

Or maybe I should regard this project as a prototype?

Maybe its only a couple of days work for him?

Maybe he's not even building it with me in mind?

Matthew

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/74.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
