### ISSUE TITLE
Group signatures for group agents

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#77]
One way group agents could make agreements with other agents:
https://github.com/dedis/cosi

> ...the CoSi protocol for scalable collective signing. CoSi enables authorities to have their statements collectively signed, or co-signed, by a scalable group of independent parties or witnesses. The signatures that CoSi produces convey the same information as a list of conventional signatures from all participants, but CoSi signatures are far more compact and efficient for clients to verify.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/77.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
