### ISSUE TITLE
Discussion of consume/create/transport snippets

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#78]
An issue to discuss @elf-pavlik snippets of yaml, the next step in working on 0.0.  Snippets are here: https://github.com/valueflows/valueflows/tree/master/snippets.  They are the material core of the process model: transformation with consume and create; transportation with load and unload.  Bikes representing serialized resources; 3d printer parts representing stock non-serialized resources.

**Comment by bhaugen** [comment]
> I'm not sure how Bob thinks about it, but I don't see how the frame can continue to be managed as part of any inventory (not sure what "such inventory" is).

I totally agree that a bike frame that has been assembled into a bike is no longer a resource, the bike is.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/78.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
