### ISSUE TITLE
Data/Media/Informational Resources

### ISSUE THREAD

**Issue by gcassel** [valueflows/forum.valueflo.ws#79]
I'm finally at a controlled "request for comments" phase with the development of my [P2P Digital Networking Protocol](https://docs.google.com/document/d/1CKXns9XKySsFGcPGnmKiM5wAWJmbeBWZY6iIljAz6a4/edit?usp=sharing) document.   

That document only relates partially to VF's goals.  However, it relates deeply to my personal focus on the immateriality of media/ informational resources.  As I've occasionally (briefly) mentioned, I believe that media resources should be fundamentally distinguished from physical resources.

**I'd appreciate ideas on how to distinguish digital media from physical resources in vf accounting.**  I'm inclined to simply suggest _vf:DataResource_, to indicate any valuable combination of data or media which networks may wish to account for in economic processes (separately from physical copies.)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/79.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
