### ISSUE TITLE
Connexion with Data Food Consortium, and Solawi project, and... data mapping...

### ISSUE THREAD

**Issue by myriamboure** [valueflows/forum.valueflo.ws#8]
Hi everyone !

I learned from the Ugrencii mail-list about the Solidbase project: https://solidbase.info/coding-start/
which I find pretty closed to what we are trying to do with Data Food Consortium project https://github.com/datafoodconsortium/ontology
After the work on the ontology we are getting into prototyping and are still hitting issues that we are trying to find commons based solutions, like unique identifier for products (should we try to work with Open Food Facts? Or build some other shared/common URI database? In a context where national agencies try to get full control over it...), agents and places, and how to manage transitions from existing platforms to a more decentralized architecture (which might need some steps, as we also manage human communities...).
We had deep reflexions on the product ontology and find some interesting path we would like to discuss. 
For the prototype we found temporary solutions, but we need to find solution for next iteration on the prorotype.

@bhaugen I think it would be great if we could plan a call to discuss further about our initiatives so that we can understand better their interconnexions and see if there are places for closer cooperation. Let's do that next week, or early January ? Maybe with Solawi people as well, and I could invite people from Denmark and Australia and the US who work on the same food platform interoperability topic. So we can share our approaches and see how to better collaborate.

Let me know what you think !

**Comment by myriamboure** [comment]
oups I didn't know you were living in this part of the world @bhaugen I thought you were in Germany, don't know why ;-) So when it's 10pm in France it's 8 am in Melbourne and 3pm in Mexico if I'm not mistaken. I could do the 19th evening (20th morning for Melbourne) or 20th evening (21st morning in Melbourne). Will bring Kirsten here, but let me know what others can.

**Comment by elf-pavlik** [comment]
:+1: This side of the clock works better for our timezone (I think with Lynn and Bob we stay on exact the same one)

On 20th I could join for sure, for 19th I already have some other plans which I would need to see if I can change in case 19th works better for everyone else.

![screenshot at 2018-12-13 12-13-58](https://user-images.githubusercontent.com/876431/49958706-36741f80-fed1-11e8-9828-a89ecf62328f.png)

[http://worldchatclock.com](http://worldchatclock.com/?a%5B0%5D%5Bname%5D=Paris&a%5B0%5D%5Btz%5D=Europe%2FParis&a%5B0%5D%5BisHome%5D=true&a%5B1%5D%5Bname%5D=Melbourne&a%5B1%5D%5Btz%5D=Australia%2FMelbourne&a%5B1%5D%5BisHome%5D=false&a%5B2%5D%5Bname%5D=Mexico+City&a%5B2%5D%5Btz%5D=America%2FMexico_City&a%5B2%5D%5BisHome%5D=false&isAP=1)

**Comment by fosterlynn** [comment]
@myriamboure @kirstenalarsen I said I would start mapping the DFC ontology with VF.  I did an initial conceptual mapping with the help of @elf-pavlik and @bhaugen .  It is here: https://docs.google.com/document/d/1ODah5xKw_QkVOLbJlKcebCfHe6LUG08Ph1X35Y_Sn0o/edit?usp=sharing.  Comments welcome!  (And sorry for double posting...)

**Comment by elf-pavlik** [comment]
Historical Data Food Consortium issue #7 (just cross referencing)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/8.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
