### ISSUE TITLE
Community-centered design and design justice

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#82]
The kinds of design I think we should do when we put VF back into participatory action research.
http://www.andalsotoo.net/generating-shared-principles-for-design-justice/

Now we just need to learn how to do it...

@unalee ? @coopchange ?

**Comment by stevebosserman** [comment]
I would like to be on the call so I can learn more about what everyone is
doing!

Thanks!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/82.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
