### ISSUE TITLE
Proposed collaboration with MAN

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#83]
Hi VF gang!  @bhaugen and I been working off and on with the [Mutual Aid Network](http://www.mutualaidnetwork.org/) in Madison WI for some time.  And commenting here about them occasionally.  Next year some time, hopefully early in the year, they are going to address interoperability between their platforms ([Wezer](http://www.valeureux.org/blog/), [Community Forge](http://communityforge.net/en), and [LocEcon](http://locecon.org/)). We proposed to do that as a collaboration between the MAN and ValueFlows, so that MAN can gain interoperability, and VF can have a concrete use case to push it forward in the world.  Stephanie from the MAN was enthusiastic about such a collaboration.  

Also in the most recent discussion was @numapanuma from GoPacifia in Argentina, who is also very interested in software interoperability.  They are planning to use NRP, and could also benefit from some of the MAN functionality.  So NRP could be part of it too, remains to be seen.

This also seems like a great time to try to work on the long discussed collaboration with TransforMap and @almereyda , as he has also had recent discussions with the MAN.

So - I'm pretty excited about the possibility.  But what do you all think?  Good step for us?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/83.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
