### ISSUE TITLE
Types of conversations for agreement and action

### ISSUE THREAD

**Issue by gcassel** [valueflows/forum.valueflo.ws#84]
I'm feeling more settled lately in many elements of my action-based philosophy, and conversations for agreement and action.  I know that *conversations for action* is of deep importance to VF, so I want to touch base at times.

Currently, one of the main subsections of **_Agreement-Based Organization_** is titled [Subjects to agree upon](https://docs.google.com/document/d/1c_xWEIay-2jyJ3Rqb6OgTxoZBJfjNW4d6w6ukXyeJk4/edit#heading=h.uqm80l3mvwep).  In that section, I now suggest eleven basic _types_ of _potentially shared understandings_.  I plan to incorporate these types in an open "conversations for agreement and action" protocol, by suggesting that agents identify (and label) conversations which aim to create *one or more* of these types.  

### **I'd like any feedback on whether this list seems rationally comprehensive, and not excessive:**

**beliefs, goals, standards, actions, processes, roles, recipes, plans, events, budgets, reports**

*Note*: "tasks" was recently eliminated from that list, and mostly absorbed into "roles".  "Actions", "recipes", "plans" and "reports" were recently added.

Here are further details from *Agreement-Based Organization.  [Subjects to agree upon](https://docs.google.com/document/d/1c_xWEIay-2jyJ3Rqb6OgTxoZBJfjNW4d6w6ukXyeJk4/edit#heading=h.uqm80l3mvwep) goes into more detail than this, although it still needs work.

- **Beliefs** indicate perceptions regarding physical and/or social forms and/or processes.  
- **Goals** indicate desired future states or conditions.
- **Standards** indicate any guidelines and rules for activities, including communications, and technical specifications for resources.
- **Actions** indicate specific acts of transformation, creation, transportation or transfer of resources or (in some cases) agents.
- **Processes** identify actions or activities which transform described inputs into described outputs.
- **Roles** indicate types of relationship which agents can have with other agents or resources.  Roles create one or more expectations and recognized rights.
- **Recipes** are specified types of intentional processes which are suggested as potentially useful to a broad range of people and groups.
- **Plans** are specific processes currently expected by one or more agents.
- **Events** indicate periods of time during which special conditions and/or activities persist.
- **Budgets** indicate the planned investment of any currencies or resources to support goals.
- **Reports** indicate actions, activities and events which have occurred, or are currently happening.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/84.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
