### ISSUE TITLE
Collaboration with http://coopdata.org/standards/

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#85]
Below is a snippet of communication on their forum, in the "introduce yourself" thread.  We have also briefly chatted with David Balkind in TransforMap's forum.

As you can read, their immediate project is a directory of coops. So that is Agent but I am posting here because there are other entities that may apply in the future.

Their data includes a lot of properties we don't have (yet) in agent.  We have the basic relationship structure that could be useful, don't know.

Although Agent is on the edge for us, it seems to me to be useful to see if we can collaborate with any economic-focused groups who are interested. 

I'll continue to communicate in their forum and cross-post here, but if anyone has thoughts along the way, please say so.
 	
Dec 6 - Lynn
Hi, this looks interesting!

I'm Lynn, living in rural Wisconsin in the US.  I'm retired, and work with my partner Bob Haugen on software to support groups creating the "next economy".  Which definitely includes cooperatives, as well as other economic experiments going on in the world.

One project we are putting time into is called ValueFlows, which lives here (scroll down).  It is intended to be a standard vocabulary for facilitating interoperability between next-economy software platforms or decentalized applications.  It is a work in progress.

I'm wondering if there are some opportunities for collaboration between our projects?  There is definitely overlap.

Anyhow, good to "meet" you....

Lynn Foster

	Devin Balkind 	
Dec 6 (21 hours ago)
Hi Lynn. Thanks for the intro.

I can certainly see some opportunities for collaboration.

The first task a number of people want to see completed is a simple data model for a cooperative business directory. 

Many such directories exist containing yellow-page-style business listings, and their data models are often very similar, but since they aren't compatible with each other, we're stuck with silo'd datasets that can't be easily merged/aggregated for analysis or other purposes.

So, our job is to define a data-model that numerous coop directories can use and build a process that allows that data model to be modified in the future so it doesn't go out of date.

In terms of ValueFlows, it seems to me we're looking at defining a model for "agents." Does that make sense?

The current and informal "spec" for this directory entry is here. Please add comments with  field level suggestions and let me know what you think should be changed and I can add items/change things, etc.

If folks have other ideas for how to advance this project please send them out to the list.

Looking forward to collaborating!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/85.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
