### ISSUE TITLE
Collaborative Experiment in Community-Centered Design for Immigrant Protection

### ISSUE THREAD

**Issue by stevebosserman** [valueflows/forum.valueflo.ws#86]
From comment in Issue #164 

> Related to the interest by @coopchange in experimenting with a hands-on collaboration opportunity focused on community-centered design, several faith-based groups and the local timebank for Columbus, OH are exploring the concept of a 'multifaith sanctuary' for the protection of immigrants in the metropolitan area. If we go for it, we will adopt governance platforms (cooperatives) and decision processes (value flows, accounting and tracking) in support of action-impact programs (gap-filling, education / training, planning) that brings people together in a collective effort to protect immigrants. 
> 
> We are writing up a [concept paper](https://github.com/valueflows/valueflows/blob/master/use-cases/multifaith-sanctuary.md) that outlines our current conversation. Hopefully, we can draft winning proposals to local grantmaking organizations that fund these kinds of endeavors. What everyone in this group is discussing would be very helpful to us in Columbus. And if we made it a joint effort, perhaps what we learn would have much broader application in other communities.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/86.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
