### ISSUE TITLE
EISPP

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#89]
@bshambaugh 's Enterprise Information System for Peer Production

I'd like to understand better how you created the demo in the video, and the wireframes, and how I can run them myself. 

How much is hand-drawn? How much is connected to live systems? Etc. I see some Web links, and also some localhost links. 

And where are you headed with this stuff?

Quotes from https://github.com/valueflows/valueflows/issues/170#issuecomment-268712034
> I like to share EISPP wireframes. Everyone I know likes them. People
inherit skepticism about the semantic web vision but as I work on it more
and associate with various people the end result is liked (
https://www.youtube.com/watch?v=JLqvnFRiP24)

> [EISPP wireframes are actually over here](http://bshambaugh.org/eispp/)

**Comment by bshambaugh** [comment]
Here is a start Bob:

http://bshambaugh.org/eispp/

-Brent Shambaugh

GitHub: https://github.com/bshambaugh
Website: http://bshambaugh.org/
LinkedIN: https://www.linkedin.com/in/brent-shambaugh-9b91259
Skype: brent.shambaugh
Twitter: https://twitter.com/Brent_Shambaugh
WebID: http://bshambaugh.org/foaf.rdf#me

**Comment by bshambaugh** [comment]
I might have to look at this again for matching up projects. Alas, they had
me sign some agreement so I can't be all that serious until March 15. I got
the EXT- RESCAL machine learning algorithm working in Python though.

https://github.com/researchstudio-sat/webofneeds/tree/master/webofneeds

For the localhost stuff I think I used LodLive and Marmotta.

https://github.com/bshambaugh/customLodliveProfiles
http://marmotta.apache.org/
https://github.com/bshambaugh/LodLive

And I tried to redo the same thing with custom code here:
https://github.com/bshambaugh/node-arc-d3

-Brent Shambaugh

GitHub: https://github.com/bshambaugh
Website: http://bshambaugh.org/
LinkedIN: https://www.linkedin.com/in/brent-shambaugh-9b91259
Skype: brent.shambaugh
Twitter: https://twitter.com/Brent_Shambaugh
WebID: http://bshambaugh.org/foaf.rdf#me

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/89.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
