### ISSUE TITLE
Using the VF vocab in plain text

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#90]
These are not exactly the VF vocab, but examples of using predecessor vocabularies in either plain or structured text.

![image](https://cloud.githubusercontent.com/assets/117439/19016922/f3af4294-87ed-11e6-813b-1cc963cd1998.png)

![image](https://cloud.githubusercontent.com/assets/117439/19016925/0a49964e-87ee-11e6-95e8-6a0793d90642.png)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/90.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
