### ISSUE TITLE
what not using ontology instead of Value Flows

### ISSUE THREAD

**Issue by Brise2** [valueflows/forum.valueflo.ws#91]
Hello everyone, 
Value Flows are a set of common vocabularies to describe flows of economic resources of all kinds within distributed economic ecosystems. 
Ontology also is used to define a common vocabulary of a domain that is Shareable. 
we can not use ontology to define a set of common vocabularies to describe flows of economic resources of all kinds within distributed economic ecosystems. 
Thank you for your help

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/91.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
