### ISSUE TITLE
The word and concept of Model is too limiting for VF

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#92]
I see in @fosterlynn 's latest UML model, which I otherwise love, that  "Model" has replaced "Resource Type". Mostly, I want to stay out of naming arguments, but this one seems wrong. It comes from Good Relations, which is a domain ontology for e-commerce, and means "goods for sale". Which is, I think, how everybody will think of it.

VF is much more general, and aims to cover all economic and potentially all ecosystem relationships. Would you apply "Model" to a workspace or lab? How about a farm field? How about a skill? How about electrical energy? How about whole wheat bread dough?

I suggest that "Resource Template"  would be adequately general, and also fit with the other names in the diagram better than "Model".

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/92.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
