### ISSUE TITLE
basic food vocab based on VF 

### ISSUE THREAD

**Issue by djodjoni** [valueflows/forum.valueflo.ws#93]
I need to prepare soon a minor food data sync mechanism so different hub nodes using different software can share data of producers and transporters. For now the data is mostly stable i.e. without transactional events. In the context of VF it is mostly Templates . 

I would like to make it as much closer to VF as soon I will need to add the full planning and observation layers. 
I would appreciate a lot if I can get some feedback on both the logic/ideology and the RDF/LOD aspects.

you can check the current ontology here 
http://openthings-cc.github.io/openthings-food/
and here
https://cdn.rawgit.com/openthings-cc/openthings-food/master/ofd-core.ttl

I also have open an issue there:
https://github.com/openthings-cc/openthings-food/issues/2

**Comment by djodjoni** [comment]
I totally agree that this would be amazing. i wanted this for a long time :)On 1 Mar 2017 17:01, Lynn Foster <notifications@github.com> wrote:
I'd like to organize call with developers

@elf-pavlik I think that would be amazing.  It would be really good to see how VF can help with this ongoing work in food.  And I agree with the use case, needs to want some interoperability.
@djodjoni you are involved with all of this, what do you think?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/93.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
