### ISSUE TITLE
agent - resource type/etc. - agent

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#94]
Both @pmackay and @djodjoni have expressed a desire for something like agent - resource type - agent.  It would basically say something like "FarmerX provides carrots to FoodHubY".  You could probably get this from commitments or past events, but what if you don't want to implement all of that?  We talked a bit about maybe trying out Intents for this.  It is kind of like an intent, but not exactly.

We also use something like this in [LocEcon](http://locecon.org), which would be theoretically happy to get this kind of data from operational systems, but in fact mostly does not have access to it, and doesn't have a way to gather it yet.

@bhaugen and I talked about this over breakfast, and I want to propose we add this structure to VF, and figure out what would be included.

Something like vf:AgentResourceFlow?

Properties: vf:provider, vf:receiver, vf:category (?? - do we need anything more specific than category?).  Might need a vf:action, although that might be 2 action verbs, need to try some things out; or maybe as long as we have the direction, that is all that is needed, I don't know.  Might need some dates/durations kind of things.  Just brainstorming.

What do people think about including something like this?  On one hand, I want to try to get a minimal agreed upon vocab released for basic REA; on the other hand, here are some needs expressed, I think good to go for it while people are actively thinking about it.  And I think there will be even higher level constructs needed for community or regional planning, which also might or might not have a link to operational data.

**Comment by djodjoni** [comment]
revised proposal of Relationship:

```
vf:AgentRelationship  a  owl:Class ;
		rdfs:comment  "An ongoing voluntary association between 2 Agents of any kind." ;
		rdfs:label    "vf:AgentRelationship" .

vf:subject  a         owl:ObjectProperty ;
		rdfs:comment  "The subject of a relationship between 2 agents." ;
		rdfs:domain   vf:AgentRelationship ;
		rdfs:label    "subject" ;
		rdfs:range    foaf:Agent .

vf:object  a          owl:ObjectProperty ;
		rdfs:comment  "The object of a relationship between 2 agents." ;
		rdfs:domain   vf:AgentRelationship ;
		rdfs:label    "object" ;
		rdfs:range    foaf:Agent .

vf:relLabel  a    owl:DatatypeProperty ;
		rdfs:comment  "A verb that describes a generic defined relationship that exists between 2 agents." ;
		rdfs:domain   vf:AgentRelationship ;
		rdfs:label    "relationship" ;
		rdfs:range    xsd:string .

#this is for the bi directional relationship

vf:AgentResourceRelationship  a  owl:Class ;
		rdfs:comment  "AgentResourceFlow relationship" ;
                rdfs:subClassOf vf:AgentRelationship .

vf:resource  a          owl:ObjectProperty ;
		rdfs:comment  "the resource that flows from subject to the object" ;
		rdfs:domain   vf:AgentRelationship ;
		rdfs:range   vf:ResourceTaxonomyItem . 
```

Considerations:

- I don;t think context is needed, it can be implied (of course I probably don;t know the whole story :)
- relLabel is previously vf:relationship which seems to be desired to only be a String value
- vf:resource range is ResourceTaxonomyItem for clarity what needs to go i there however it can very well be anything at all 
- any more specific relations can be subclassed and/or new properties being added to clarify the relation in more detail.

These constructs are to be used for relations we cannot forsee otherwise it is better to define owl Properties of course.

AgentResourceRelationship relations should normally be extractable from actual plan or observation layers, but they are useful so that less complex data is transmitted, saved and displayed by various applications.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/94.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
