### ISSUE TITLE
Semantic blockchains

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#95]
https://lists.w3.org/Archives/Public/public-webpayments/2017Mar/0000.html
Follow the thread.
https://semanticblocks.files.wordpress.com/2017/03/linked_blockchain_paper.pdf
https://www.slideshare.net/bengardner135/semantic-blockchain
https://lists.w3.org/Archives/Public/public-webpayments/2017Mar/0003.html

That last one should be VF, not NRP. @elf-pavlik - are you part of that w3c group?

Or, wait wait, might be able to ping @melvincarvalho ...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/95.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
