### ISSUE TITLE
Linked Data Platform Based NRP Logger

### ISSUE THREAD

**Issue by bshambaugh** [valueflows/forum.valueflo.ws#96]
I was daydreaming about what sorts of linked data applications I'd like to build. In function borrowing from this: https://www.youtube.com/watch?v=SsWJbdsq9H4 [ch_1_2_edit_triples (Edit Triples) - EISPP] (but not necessarily in form).

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/96.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
