### ISSUE TITLE
Enspiral Root Systems as a VF case study?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#97]
![the Roots](https://cdn-images-1.medium.com/max/600/1*gLeNxK8TszCmyryxho1ahw.jpeg)

# [Root Systems](https://www.rootsystems.nz/)

... are an experimental form of organization called by Enspiralites a "Livelihood Pod", which they say is [a new financial model for consulting](https://medium.com/enspiral-tales/a-new-financial-model-for-consulting-c7781661a1ec).

In @gcassel 's terms, they are an [Agreement-Based Organization](https://medium.com/enspiral-tales/a-developmental-framework-for-agreement-based-organization-54298b128906). They are developing a set of written [Agreements](https://www.rootsystems.nz/agreements/readme.html).

They are clearly a group Agent, making [agreements as a group with other Livelihood Pods](https://www.rootsystems.nz/agreements/golden-pandas.html).

They have in particular a [Financial Agreement](https://www.rootsystems.nz/agreements/financial_agreement.html) and intend to document their financial flows and generate a monthly [cash flow report](https://www.valueflo.ws/appendix/cashflows.html).

In their [plan](https://www.rootsystems.nz/context/plan.html), they want to develop an "Ecosystem of Livelihood Pods", and also organize their Supply Network:
> Our intervention is to develop a protocol to standardise the data shape to share information between supply chain actors. This protocol will allow for a new type of coordination, one more intentional. The market will be able to communicate their requirements to the supply network and find values aligned suppliers to meet the demand. The supply network will also be able to communicate with various markets finding out more specifically what the demand is, this way coordinating availibility with the demand.

> This will lead to a transparent supply network. Where anyone may start supplying and be informed of what the market demands.

> We will end up with a supply network that is more human

I think they may be the first consciously VF:Organization. What shall we do about this? (Beyond celebrate them.) :tada: :fireworks: :rocket: :joy_cat:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/97.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
